-- Event bingo live rounds and winner tracking

CREATE TABLE IF NOT EXISTS `event_bingo_round_instances` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT NOT NULL,
  `event_id` BIGINT NOT NULL,
  `round_number` INT NOT NULL,
  `bingo_game_id` BIGINT NULL,
  `name` VARCHAR(255) NOT NULL,
  `pattern` VARCHAR(512) NOT NULL,
  `difficulty` VARCHAR(32) NOT NULL,
  `assigned_prize` VARCHAR(255) NOT NULL,
  `prize_cost` DECIMAL(12, 2) NULL,
  `prize_retail_value` DECIMAL(12, 2) NULL,
  `scheduled_at` DATETIME(3) NULL,
  `actual_start_at` DATETIME(3) NULL,
  `actual_end_at` DATETIME(3) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'scheduled',
  `created_by_id` BIGINT NULL,
  `updated_by_id` BIGINT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `event_bingo_round_instances_event_id_round_number_key` (`event_id`, `round_number`),
  INDEX `event_bingo_round_instances_organization_id_event_id_status_idx` (`organization_id`, `event_id`, `status`),
  CONSTRAINT `event_bingo_round_instances_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_bingo_round_instances_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `lms_events`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_bingo_round_instances_bingo_game_id_fkey` FOREIGN KEY (`bingo_game_id`) REFERENCES `event_bingo_games`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_bingo_winners` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT NOT NULL,
  `event_id` BIGINT NOT NULL,
  `round_instance_id` BIGINT NOT NULL,
  `bingo_game_id` BIGINT NULL,
  `registration_id` BIGINT NOT NULL,
  `winning_card_number` VARCHAR(64) NOT NULL,
  `card_type` VARCHAR(32) NOT NULL DEFAULT 'included',
  `prize_label` VARCHAR(255) NOT NULL,
  `prize_cost` DECIMAL(12, 2) NULL,
  `prize_retail_value` DECIMAL(12, 2) NULL,
  `verified` BOOLEAN NOT NULL DEFAULT false,
  `verified_by_id` BIGINT NULL,
  `verified_at` DATETIME(3) NULL,
  `verification_notes` TEXT NULL,
  `winner_photo_url` VARCHAR(2048) NULL,
  `notes` TEXT NULL,
  `invalidated` BOOLEAN NOT NULL DEFAULT false,
  `created_by_id` BIGINT NULL,
  `updated_by_id` BIGINT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `event_bingo_winners_organization_id_event_id_idx` (`organization_id`, `event_id`),
  INDEX `event_bingo_winners_round_instance_id_idx` (`round_instance_id`),
  INDEX `event_bingo_winners_registration_id_idx` (`registration_id`),
  CONSTRAINT `event_bingo_winners_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_bingo_winners_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `lms_events`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_bingo_winners_round_instance_id_fkey` FOREIGN KEY (`round_instance_id`) REFERENCES `event_bingo_round_instances`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_bingo_winners_registration_id_fkey` FOREIGN KEY (`registration_id`) REFERENCES `lms_event_registrations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_bingo_winners_verified_by_id_fkey` FOREIGN KEY (`verified_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `event_bingo_winners_created_by_id_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
