import hostJamie from "@/assets/host-jamie.jpg";
import hostMorgan from "@/assets/host-morgan.jpg";
import hostAlex from "@/assets/host-alex.jpg";
import hostSam from "@/assets/host-sam.jpg";
import hostRiley from "@/assets/host-riley.jpg";
import hostTaylor from "@/assets/host-taylor.jpg";

export type EventDetail = {
  slug: string;
  month: string;
  day: string;
  year: number;
  city: string;
  state: string;
  venue: string;
  day_name: string;
  doorsOpen: string;
  time: string;
  endTime: string;
  left: number;
  price: number;
  tint: string;
  address: string;
  venuePhone: string;
  under21: boolean;
  foodAndDrinks: string;
  host: { name: string; bio: string; image: string };
  sponsor: { name: string; address: string; phone: string; perk: string };
  soldOut?: boolean;
};

export const events: EventDetail[] = [
  {
    slug: "dallas-07-08-celestial",
    month: "JUL", day: "08", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Celestial",
    day_name: "Wednesday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 0, price: 30, tint: "bg-lime/20", soldOut: true,
    address: "2530 S Lamar St, Dallas, TX 75215",
    venuePhone: "(214) 434-0088",
    under21: true,
    foodAndDrinks: "Full craft beer menu with rotating food trucks and outdoor patio.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "dallas-07-09-oak-cliff-brewing",
    month: "JUL", day: "09", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Oak Cliff Brewing",
    day_name: "Thursday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 0, price: 30, tint: "bg-blossom/20", soldOut: true,
    address: "1111 S Beckley Ave, Dallas, TX 75208",
    venuePhone: "(214) 555-0142",
    under21: true,
    foodAndDrinks: "Neighborhood brewery with craft beer, cocktails, and rotating local food pop-ups.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "dallas-07-09-lakewood-brewing",
    month: "JUL", day: "09", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Lakewood Brewing",
    day_name: "Thursday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 21, price: 30, tint: "bg-sunny/25",
    address: "2302 Executive Dr, Garland, TX 75041",
    venuePhone: "(972) 555-0183",
    under21: true,
    foodAndDrinks: "Spacious taproom with craft beer lineup and on-site food trucks.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "dallas-07-11-chicken-n-pickle-grapevin",
    month: "JUL", day: "11", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Chicken N Pickle Grapevine",
    day_name: "Saturday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 37, price: 30, tint: "bg-sky-blue/25",
    address: "728 Gateway Blvd, Grapevine, TX 76051",
    venuePhone: "(817) 555-0127",
    under21: true,
    foodAndDrinks: "Full restaurant and bar with indoor/outdoor pickleball courts and lawn games.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "austin-jul-12",
    month: "JUL", day: "12", year: 2026,
    city: "Austin", state: "Texas",
    venue: "Lucille Patio Lounge",
    day_name: "Sunday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 45, price: 30, tint: "bg-lime/20",
    address: "77 Rainey St, Austin, TX 78701",
    venuePhone: "(512) 480-0086",
    under21: true,
    foodAndDrinks: "Full outdoor patio bar with craft cocktails and small plates.",
    host: { name: "Sam Delgado", bio: "Fifth-generation Texan and cactus obsessive. Sam calls every Central Texas Plant Bingo night.", image: hostSam },
    sponsor: { name: "The Great Outdoors Nursery", address: "2730 S Congress Ave, Austin, TX 78704", phone: "(512) 448-2992", perk: "Every attendee gets a discount card — visit The Great Outdoors to redeem." },
  },
  {
    slug: "dallas-07-12-odd-muse-book-bingo-roman",
    month: "JUL", day: "12", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Odd Muse (Book Bingo: Romance)",
    day_name: "Sunday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 35, price: 30, tint: "bg-lime/20",
    address: "13845 N Stemmons Fwy, Farmers Branch, TX 75234",
    venuePhone: "(972) 555-0164",
    under21: true,
    foodAndDrinks: "Creative brewery taproom with craft beers and light bites.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "austin-jul-13",
    month: "JUL", day: "13", year: 2026,
    city: "Austin", state: "Texas",
    venue: "Central District Brewing",
    day_name: "Monday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 52, price: 30, tint: "bg-blossom/20",
    address: "417 Red River St, Austin, TX 78701",
    venuePhone: "(512) 494-0328",
    under21: true,
    foodAndDrinks: "Rotating craft beer selection and local food truck partnerships.",
    host: { name: "Sam Delgado", bio: "Fifth-generation Texan and cactus obsessive. Sam calls every Central Texas Plant Bingo night.", image: hostSam },
    sponsor: { name: "The Great Outdoors Nursery", address: "2730 S Congress Ave, Austin, TX 78704", phone: "(512) 448-2992", perk: "Every attendee gets a discount card — visit The Great Outdoors to redeem." },
  },
  {
    slug: "dallas-07-16-tupps",
    month: "JUL", day: "16", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "TUPPS",
    day_name: "Thursday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 34, price: 30, tint: "bg-blossom/20",
    address: "721 Anderson St, McKinney, TX 75069",
    venuePhone: "(214) 555-0195",
    under21: true,
    foodAndDrinks: "Historic cotton mill brewery with full bar and rotating food trucks.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "dallas-07-18-chicken-n-pickle-grand-pr",
    month: "JUL", day: "18", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Chicken N Pickle Grand Prairie",
    day_name: "Saturday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 28, price: 30, tint: "bg-sunny/25",
    address: "2701 Market Loop, Grand Prairie, TX 75052",
    venuePhone: "(972) 555-0138",
    under21: true,
    foodAndDrinks: "Full restaurant and bar with indoor/outdoor pickleball courts and lawn games.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "austin-jul-20",
    month: "JUL", day: "20", year: 2026,
    city: "Austin", state: "Texas",
    venue: "Lazarus E. 6th",
    day_name: "Monday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 38, price: 30, tint: "bg-sunny/25",
    address: "1902 E 6th St, Austin, TX 78702",
    venuePhone: "(512) 524-5180",
    under21: true,
    foodAndDrinks: "In-house brewery with wood-fired pizza and full bar.",
    host: { name: "Sam Delgado", bio: "Fifth-generation Texan and cactus obsessive. Sam calls every Central Texas Plant Bingo night.", image: hostSam },
    sponsor: { name: "The Great Outdoors Nursery", address: "2730 S Congress Ave, Austin, TX 78704", phone: "(512) 448-2992", perk: "Every attendee gets a discount card — visit The Great Outdoors to redeem." },
  },
  {
    slug: "dallas-07-23-acacia-collective",
    month: "JUL", day: "23", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Acacia Collective",
    day_name: "Thursday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 26, price: 30, tint: "bg-sky-blue/25",
    address: "1901 S Lamar St, Dallas, TX 75215",
    venuePhone: "(214) 555-0171",
    under21: true,
    foodAndDrinks: "Plant-forward cafe and bar with craft cocktails and small plates.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "jacksonville-jul-24",
    month: "JUL", day: "24", year: 2026,
    city: "Jacksonville", state: "Florida",
    venue: "Intuition Ale Works",
    day_name: "Saturday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 24, price: 30, tint: "bg-lime/20",
    address: "929 E Bay St, Jacksonville, FL 32202",
    venuePhone: "(904) 683-7720",
    under21: true,
    foodAndDrinks: "Full venue bar plus on-site kitchen with wood-fired pizza and shareables.",
    host: { name: "Jamie Rivera", bio: "Plant Bingo co-founder and lifelong plant collector. Jamie has hosted 200+ events across the Southeast and always brings the good energy (and the good plants).", image: hostJamie },
    sponsor: { name: "Liberty Landscape Supply", address: "9101 Philips Hwy, Jacksonville, FL 32256", phone: "(904) 683-7100", perk: "Every attendee gets a discount card — visit Liberty Landscape Supply to redeem." },
  },
  {
    slug: "austin-jul-25",
    month: "JUL", day: "25", year: 2026,
    city: "Austin", state: "Texas",
    venue: "Meanwhile Brewing",
    day_name: "Saturday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 61, price: 30, tint: "bg-sky-blue/25",
    address: "3901 Promontory Point Dr, Austin, TX 78744",
    venuePhone: "(512) 593-4996",
    under21: true,
    foodAndDrinks: "Sprawling beer garden with food trucks, lawn games, and outdoor patio.",
    host: { name: "Sam Delgado", bio: "Fifth-generation Texan and cactus obsessive. Sam calls every Central Texas Plant Bingo night.", image: hostSam },
    sponsor: { name: "The Great Outdoors Nursery", address: "2730 S Congress Ave, Austin, TX 78704", phone: "(512) 448-2992", perk: "Every attendee gets a discount card — visit The Great Outdoors to redeem." },
  },
  {
    slug: "dallas-07-25-chicken-n-pickle-allen",
    month: "JUL", day: "25", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Chicken N Pickle Allen",
    day_name: "Saturday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 63, price: 30, tint: "bg-lime/20",
    address: "730 Cottonwood Creek Rd, Allen, TX 75002",
    venuePhone: "(972) 555-0156",
    under21: true,
    foodAndDrinks: "Full restaurant and bar with indoor/outdoor pickleball courts and lawn games.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "austin-jul-26",
    month: "JUL", day: "26", year: 2026,
    city: "Austin", state: "Texas",
    venue: "Jester King Brewery",
    day_name: "Sunday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 33, price: 30, tint: "bg-blossom/20",
    address: "13187 Fitzhugh Rd, Austin, TX 78736",
    venuePhone: "(512) 523-2961",
    under21: true,
    foodAndDrinks: "Farmhouse brewery with scenic Hill Country views and on-site restaurant.",
    host: { name: "Sam Delgado", bio: "Fifth-generation Texan and cactus obsessive. Sam calls every Central Texas Plant Bingo night.", image: hostSam },
    sponsor: { name: "The Great Outdoors Nursery", address: "2730 S Congress Ave, Austin, TX 78704", phone: "(512) 448-2992", perk: "Every attendee gets a discount card — visit The Great Outdoors to redeem." },
  },
  {
    slug: "dallas-07-26-four-corners",
    month: "JUL", day: "26", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Four Corners",
    day_name: "Sunday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 54, price: 30, tint: "bg-blossom/20",
    address: "1311 S Ervay St, Dallas, TX 75215",
    venuePhone: "(214) 555-0109",
    under21: true,
    foodAndDrinks: "Deep Ellum brewery with craft beer, cocktails, and rotating food trucks.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "asheville-jul-27",
    month: "JUL", day: "27", year: 2026,
    city: "Asheville", state: "North Carolina",
    venue: "Wedge Brewing Co.",
    day_name: "Tuesday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 42, price: 30, tint: "bg-blossom/20",
    address: "37 Paynes Way #001, Asheville, NC 28801",
    venuePhone: "(828) 505-2792",
    under21: true,
    foodAndDrinks: "Rotating food trucks on-site and a full craft beer bar.",
    host: { name: "Morgan Lee", bio: "Botanist, bingo caller, and unrepentant orchid hoarder. Morgan hosts every Blue Ridge stop of Plant Bingo.", image: hostMorgan },
    sponsor: { name: "B.B. Barns Garden Center", address: "3653 Sweeten Creek Rd, Arden, NC 28704", phone: "(828) 650-7300", perk: "Every attendee gets a discount card — visit B.B. Barns to redeem." },
  },
  {
    slug: "dallas-07-29-community",
    month: "JUL", day: "29", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Community",
    day_name: "Wednesday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 25, price: 30, tint: "bg-sunny/25",
    address: "1530 Inspiration Dr, Dallas, TX 75207",
    venuePhone: "(214) 555-0115",
    under21: true,
    foodAndDrinks: "Large brewery with full bar, event space, and on-site food partners.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "austin-aug-02",
    month: "AUG", day: "02", year: 2026,
    city: "Austin", state: "Texas",
    venue: "Oak Hill Social",
    day_name: "Sunday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 29, price: 30, tint: "bg-sunny/25",
    address: "5700 W Slaughter Ln, Austin, TX 78749",
    venuePhone: "(512) 555-0199",
    under21: true,
    foodAndDrinks: "Neighborhood social house with craft cocktails and weekend food pop-ups.",
    host: { name: "Sam Delgado", bio: "Fifth-generation Texan and cactus obsessive. Sam calls every Central Texas Plant Bingo night.", image: hostSam },
    sponsor: { name: "The Great Outdoors Nursery", address: "2730 S Congress Ave, Austin, TX 78704", phone: "(512) 448-2992", perk: "Every attendee gets a discount card — visit The Great Outdoors to redeem." },
  },
  {
    slug: "portland-aug-03",
    month: "AUG", day: "03", year: 2026,
    city: "Portland", state: "Oregon",
    venue: "Cascade Barrel House",
    day_name: "Saturday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 12, price: 30, tint: "bg-sunny/25",
    address: "939 SE Belmont St, Portland, OR 97214",
    venuePhone: "(503) 265-8603",
    under21: false,
    foodAndDrinks: "Full sour-beer bar and rotating small-plates menu. 21+ only.",
    host: { name: "Alex Chen", bio: "PNW plant nerd and stand-up comic. Alex hosts every Cascadia stop and makes sure nobody leaves without a laugh.", image: hostAlex },
    sponsor: { name: "Portland Nursery", address: "5050 SE Stark St, Portland, OR 97215", phone: "(503) 231-5050", perk: "Every attendee gets a discount card — visit Portland Nursery to redeem." },
  },
  {
    slug: "austin-aug-03",
    month: "AUG", day: "03", year: 2026,
    city: "Austin", state: "Texas",
    venue: "Prost Alehouse",
    day_name: "Monday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 55, price: 30, tint: "bg-lime/20",
    address: "411 E Main St, Round Rock, TX 78664",
    venuePhone: "(512) 382-6237",
    under21: true,
    foodAndDrinks: "German-style beer hall with authentic pretzels, sausages, and full bar.",
    host: { name: "Sam Delgado", bio: "Fifth-generation Texan and cactus obsessive. Sam calls every Central Texas Plant Bingo night.", image: hostSam },
    sponsor: { name: "The Great Outdoors Nursery", address: "2730 S Congress Ave, Austin, TX 78704", phone: "(512) 448-2992", perk: "Every attendee gets a discount card — visit The Great Outdoors to redeem." },
  },
  {
    slug: "dallas-08-04-oak-cliff-brewing-book-bi",
    month: "AUG", day: "04", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Oak Cliff Brewing (Book Bingo: SciFi/Fantasy)",
    day_name: "Tuesday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 57, price: 30, tint: "bg-sky-blue/25",
    address: "1111 S Beckley Ave, Dallas, TX 75208",
    venuePhone: "(214) 555-0142",
    under21: true,
    foodAndDrinks: "Neighborhood brewery with craft beer, cocktails, and rotating local food pop-ups.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "dallas-08-05-celestial",
    month: "AUG", day: "05", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Celestial",
    day_name: "Wednesday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 47, price: 30, tint: "bg-lime/20",
    address: "2530 S Lamar St, Dallas, TX 75215",
    venuePhone: "(214) 434-0088",
    under21: true,
    foodAndDrinks: "Full craft beer menu with rotating food trucks and outdoor patio.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "dallas-08-06-white-rock-brewing",
    month: "AUG", day: "06", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "White Rock Brewing",
    day_name: "Thursday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 22, price: 30, tint: "bg-blossom/20",
    address: "7331 Gaston Ave, Dallas, TX 75214",
    venuePhone: "(214) 555-0187",
    under21: true,
    foodAndDrinks: "Brewery and taproom with craft beer and seasonal food truck partners.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "austin-aug-10",
    month: "AUG", day: "10", year: 2026,
    city: "Austin", state: "Texas",
    venue: "Live Oak Brewing",
    day_name: "Saturday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 68, price: 30, tint: "bg-sky-blue/25",
    address: "1615 Crozier Ln, Del Valle, TX 78617",
    venuePhone: "(512) 385-2299",
    under21: true,
    foodAndDrinks: "Beer garden bar and weekly food truck lineup.",
    host: { name: "Sam Delgado", bio: "Fifth-generation Texan and cactus obsessive. Sam calls every Central Texas Plant Bingo night.", image: hostSam },
    sponsor: { name: "The Great Outdoors Nursery", address: "2730 S Congress Ave, Austin, TX 78704", phone: "(512) 448-2992", perk: "Every attendee gets a discount card — visit The Great Outdoors to redeem." },
  },
  {
    slug: "dallas-08-13-chicken-n-pickle-grapevin",
    month: "AUG", day: "13", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Chicken N Pickle Grapevine",
    day_name: "Thursday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 21, price: 30, tint: "bg-sunny/25",
    address: "728 Gateway Blvd, Grapevine, TX 76051",
    venuePhone: "(817) 555-0127",
    under21: true,
    foodAndDrinks: "Full restaurant and bar with indoor/outdoor pickleball courts and lawn games.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "dallas-08-13-puttery-plant-bingo-and-m",
    month: "AUG", day: "13", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Puttery (Plant Bingo & Mini Golf)",
    day_name: "Thursday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 25, price: 30, tint: "bg-sky-blue/25",
    address: "2425 Victory Park Ln, Dallas, TX 75219",
    venuePhone: "(214) 555-0169",
    under21: true,
    foodAndDrinks: "Upscale mini golf venue with full bar and chef-driven shareable plates.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "denver-aug-17",
    month: "AUG", day: "17", year: 2026,
    city: "Denver", state: "Colorado",
    venue: "Great Divide Brewing",
    day_name: "Saturday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 31, price: 30, tint: "bg-lime/20",
    address: "2201 Arapahoe St, Denver, CO 80205",
    venuePhone: "(303) 296-9460",
    under21: true,
    foodAndDrinks: "Full venue bar. Food trucks parked outside every event night.",
    host: { name: "Riley Nakamura", bio: "Mile-high plant tour guide and Plant Bingo veteran host. Riley knows every houseplant by name — and yours too by the end of the night.", image: hostRiley },
    sponsor: { name: "Tagawa Gardens", address: "7711 S Parker Rd, Centennial, CO 80016", phone: "(303) 690-4722", perk: "Every attendee gets a discount card — visit Tagawa Gardens to redeem." },
  },
  {
    slug: "dallas-08-20-chicken-n-pickle-grand-pr",
    month: "AUG", day: "20", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Chicken N Pickle Grand Prairie",
    day_name: "Thursday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 33, price: 30, tint: "bg-lime/20",
    address: "2701 Market Loop, Grand Prairie, TX 75052",
    venuePhone: "(972) 555-0138",
    under21: true,
    foodAndDrinks: "Full restaurant and bar with indoor/outdoor pickleball courts and lawn games.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
  {
    slug: "nashville-aug-24",
    month: "AUG", day: "24", year: 2026,
    city: "Nashville", state: "Tennessee",
    venue: "Yazoo Brewing Co.",
    day_name: "Saturday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 56, price: 30, tint: "bg-blossom/20",
    address: "900 River Bluff Dr, Madison, TN 37115",
    venuePhone: "(615) 891-4649",
    under21: true,
    foodAndDrinks: "Taproom bar with rotating Nashville food trucks.",
    host: { name: "Taylor Brooks", bio: "Music City host with a monstera collection to rival any radio playlist. Taylor's been calling bingo since college.", image: hostTaylor },
    sponsor: { name: "Bates Nursery & Garden Center", address: "3810 Whites Creek Pike, Nashville, TN 37207", phone: "(615) 876-1014", perk: "Every attendee gets a discount card — visit Bates Nursery to redeem." },
  },
  {
    slug: "dallas-08-30-chicken-n-pickle-allen",
    month: "AUG", day: "30", year: 2026,
    city: "Dallas / Fort Worth", state: "Texas",
    venue: "Chicken N Pickle Allen",
    day_name: "Sunday", doorsOpen: "5:30 PM", time: "7:00 PM", endTime: "9:00 PM",
    left: 34, price: 30, tint: "bg-blossom/20",
    address: "730 Cottonwood Creek Rd, Allen, TX 75002",
    venuePhone: "(972) 555-0156",
    under21: true,
    foodAndDrinks: "Full restaurant and bar with indoor/outdoor pickleball courts and lawn games.",
    host: { name: "Jordan Reyes", bio: "DFW native and houseplant enthusiast. Jordan brings big energy to every Dallas / Fort Worth Plant Bingo night.", image: hostTaylor },
    sponsor: { name: "North Haven Gardens", address: "7700 Northaven Rd, Dallas, TX 75230", phone: "(214) 350-9008", perk: "Every attendee gets a discount card — visit North Haven Gardens to redeem." },
  },
];

export function getEventBySlug(slug: string) {
  return events.find((e) => e.slug === slug);
}