import type { CommissionOverviewPayload } from "@/lib/event-platform/commissions/commission-overview-types";

function trend(amount: number, change: number, suffix = "vs previous period") {
  const sign = change > 0 ? "+" : "";
  return {
    amount,
    value: amount,
    change,
    changeLabel: change === 0 ? `0% ${suffix}` : `${sign}${change}% ${suffix}`,
    direction: change > 0 ? ("up" as const) : change < 0 ? ("down" as const) : ("flat" as const),
  };
}

/** Static overview data matching the Event Platform commission mockup. */
export function commissionOverviewDemo(globalRate = 10): CommissionOverviewPayload {
  return {
    ok: true,
    isDemo: true,
    globalCommissionRate: globalRate,
    periodLabel: "May 1 – May 31, 2026",
    kpis: {
      grossSales: trend(45678.9, 21.7),
      platformCommission: trend(4567.89, 21.7),
      paidCommission: trend(3250, 12.4),
      pendingCommission: trend(1317.89, -8.6),
      refundedCommission: trend(0, 0),
    },
    trend: [
      { month: "Dec 2025", grossSales: 28400, platformCommission: 2840 },
      { month: "Jan 2026", grossSales: 31200, platformCommission: 3120 },
      { month: "Feb 2026", grossSales: 29800, platformCommission: 2980 },
      { month: "Mar 2026", grossSales: 36500, platformCommission: 3650 },
      { month: "Apr 2026", grossSales: 40100, platformCommission: 4010 },
      { month: "May 2026", grossSales: 45678.9, platformCommission: 4567.89 },
    ],
    recentLedger: [
      {
        id: "demo-1",
        date: "2026-05-28",
        bookingId: "BK-87291",
        eventTitle: "CPR & First Aid Certification",
        vendorName: "Metro CPR Training Co",
        grossAmount: "149.00",
        commissionPercent: "12",
        platformCommission: "17.88",
        vendorNet: "131.12",
        currency: "USD",
        status: "paid",
      },
      {
        id: "demo-2",
        date: "2026-05-27",
        bookingId: "BK-87245",
        eventTitle: "Fire Safety Training",
        vendorName: "Urban Events LLC",
        grossAmount: "89.00",
        commissionPercent: "10",
        platformCommission: "8.90",
        vendorNet: "80.10",
        currency: "USD",
        status: "pending",
      },
      {
        id: "demo-3",
        date: "2026-05-26",
        bookingId: "BK-87201",
        eventTitle: "Summer Festival Booth",
        vendorName: "Central Park Events",
        grossAmount: "250.00",
        commissionPercent: "15",
        platformCommission: "37.50",
        vendorNet: "212.50",
        currency: "USD",
        status: "batched",
      },
      {
        id: "demo-4",
        date: "2026-05-24",
        bookingId: "BK-87123",
        eventTitle: "Yoga & Wellness Retreat",
        vendorName: "Mindful Living Inc",
        grossAmount: "75.00",
        commissionPercent: "10",
        platformCommission: "7.50",
        vendorNet: "67.50",
        currency: "USD",
        status: "paid",
      },
      {
        id: "demo-5",
        date: "2026-05-23",
        bookingId: "BK-87098",
        eventTitle: "Kids Art Workshop",
        vendorName: "Creative Minds Academy",
        grossAmount: "45.00",
        commissionPercent: "10",
        platformCommission: "4.50",
        vendorNet: "40.50",
        currency: "USD",
        status: "paid",
      },
      {
        id: "demo-6",
        date: "2026-05-22",
        bookingId: "BK-87056",
        eventTitle: "Plant Bingo Night",
        vendorName: "The Social Greenhouse",
        grossAmount: "50.00",
        commissionPercent: "10",
        platformCommission: "5.00",
        vendorNet: "45.00",
        currency: "USD",
        status: "pending",
      },
    ],
    ledgerTotal: 256,
    vendorPlans: [
      {
        id: "vp-1",
        vendorName: "Metro CPR Training Co",
        planType: "custom",
        commissionRate: "12",
        eventsCount: 8,
        earnedToDate: "1842.50",
      },
      {
        id: "vp-2",
        vendorName: "Urban Events LLC",
        planType: "default",
        commissionRate: "10",
        eventsCount: 5,
        earnedToDate: "920.00",
      },
      {
        id: "vp-3",
        vendorName: "Central Park Events",
        planType: "custom",
        commissionRate: "15",
        eventsCount: 3,
        earnedToDate: "1125.00",
      },
      {
        id: "vp-4",
        vendorName: "The Social Greenhouse",
        planType: "default",
        commissionRate: "10",
        eventsCount: 12,
        earnedToDate: "680.39",
      },
    ],
    commissionRules: [
      {
        id: "cr-1",
        eventTitle: "CPR & First Aid Certification",
        vendorName: "Metro CPR Training Co",
        commissionRate: "12",
        isActive: true,
      },
      {
        id: "cr-2",
        eventTitle: "Summer Festival Booth",
        vendorName: "Central Park Events",
        commissionRate: "15",
        isActive: true,
      },
      {
        id: "cr-3",
        eventTitle: "Plant Bingo Night",
        vendorName: "The Social Greenhouse",
        commissionRate: "10",
        isActive: true,
      },
      {
        id: "cr-4",
        eventTitle: "Fire Safety Training",
        vendorName: "Urban Events LLC",
        commissionRate: "10",
        isActive: false,
      },
    ],
  };
}
