import type {
  LmsEvent,
  LmsEventCategory,
  LmsEventCertificate,
  LmsEventIncomeReport,
  LmsEventNotification,
  LmsEventOrganizerKpis,
  LmsEventRegistration,
  LmsEventSupportTicket,
  LmsEventTicket,
  LmsEventTransaction,
  LmsEventWishlistItem,
} from "@/lib/lms-events/types";

const ORG = "1000";
const NOW = new Date();

function iso(d: Date): string {
  return d.toISOString();
}

function addDays(base: Date, days: number, hour = 9): Date {
  const x = new Date(base);
  x.setDate(x.getDate() + days);
  x.setHours(hour, 0, 0, 0);
  return x;
}

function auditFields(id: string) {
  return {
    id,
    organizationId: ORG,
    createdAt: iso(addDays(NOW, -30)),
    updatedAt: iso(NOW),
    createdById: "1000",
    updatedById: "1000",
  };
}

function baseFields(id: string, status: LmsEvent["status"]) {
  return {
    ...auditFields(id),
    status,
  };
}

export const MOCK_LMS_EVENT_CATEGORIES: LmsEventCategory[] = [
  {
    ...auditFields("cat-cert"),
    status: "published",
    name: "Certification",
    slug: "certification",
    description: "Certification and recertification classes",
    sortOrder: 1,
  },
  {
    ...auditFields("cat-medical"),
    status: "published",
    name: "Medical training",
    slug: "medical-training",
    description: "CPR, first aid, and clinical refreshers",
    sortOrder: 2,
  },
  {
    ...auditFields("cat-compliance"),
    status: "published",
    name: "Compliance",
    slug: "compliance",
    description: "Background checks and regulatory workshops",
    sortOrder: 3,
  },
];

export const MOCK_LMS_EVENTS: LmsEvent[] = [
  {
    ...baseFields("evt-cpr-recert", "registration_open"),
    title: "CPR Recertification — Hands-On Lab",
    slug: "cpr-recertification-hands-on",
    description:
      "Renew your CPR certification with instructor-led skills practice and scenario drills for field responders.",
    shortDescription: "Hands-on CPR recertification for active responders.",
    imageUrl: "/uploads/lms/events/cpr-lab.jpg",
    categoryId: "cat-medical",
    categoryName: "Medical training",
    eventType: "cpr_class",
    deliveryMode: "in_person",
    instructorName: "Dr. Elena Marsh",
    instructorUserId: "1010",
    startsAt: iso(addDays(NOW, 14, 9)),
    endsAt: iso(addDays(NOW, 14, 13)),
    timezone: "America/New_York",
    venueName: "First Aid Responders Training Center",
    venueAddress: "1200 Market Street",
    venueCity: "Philadelphia",
    venueState: "PA",
    venuePostalCode: "19107",
    venueCountry: "US",
    venueLat: 39.9526,
    venueLng: -75.1652,
    onlineMeetingUrl: null,
    capacity: 24,
    registeredCount: 18,
    seatsRemaining: 6,
    isPublic: true,
    isFree: false,
    priceFrom: 89,
    currency: "USD",
    certificationAvailable: true,
    certificationName: "CPR Recertification",
    requirements: "Current or recently lapsed CPR card. Closed-toe shoes required.",
    cancellationPolicy: "Full refund up to 7 days before the event.",
    isFeatured: false,
    ageRule: null,
    doorsOpen: null,
    bingoStart: null,
    venueType: null,
    cardsIncluded: null,
    extraCardPrice: null,
    foodAndDrinks: null,
    attire: null,
    linkedCourseId: null,
    linkedLiveSessionId: null,
    revenueTotal: 1602,
  },
  {
    ...baseFields("evt-bg-workshop", "registration_open"),
    title: "Background Check Compliance Workshop",
    slug: "background-check-compliance-workshop",
    description:
      "Learn how to turn screening workflows into revenue while staying compliant with FCRA and state rules.",
    shortDescription: "Compliance workshop for screening resellers.",
    imageUrl: null,
    categoryId: "cat-compliance",
    categoryName: "Compliance",
    eventType: "background_check_workshop",
    deliveryMode: "online",
    instructorName: "Jordan Lee",
    instructorUserId: "1010",
    startsAt: iso(addDays(NOW, 21, 13)),
    endsAt: iso(addDays(NOW, 21, 16)),
    timezone: "America/New_York",
    venueName: null,
    venueAddress: null,
    venueCity: null,
    venueState: null,
    venuePostalCode: null,
    venueCountry: null,
    venueLat: null,
    venueLng: null,
    onlineMeetingUrl: "https://meet.example.com/bg-workshop",
    capacity: 100,
    registeredCount: 42,
    seatsRemaining: 58,
    isPublic: true,
    isFree: true,
    priceFrom: 0,
    currency: "USD",
    certificationAvailable: false,
    certificationName: null,
    requirements: "Laptop with stable internet connection.",
    cancellationPolicy: "Cancel anytime before start.",
    isFeatured: false,
    ageRule: null,
    doorsOpen: null,
    bingoStart: null,
    venueType: null,
    cardsIncluded: null,
    extraCardPrice: null,
    foodAndDrinks: null,
    attire: null,
    linkedCourseId: null,
    linkedLiveSessionId: null,
    revenueTotal: 0,
  },
  {
    ...baseFields("evt-medical-lead", "published"),
    title: "Event Medical Team Lead Intensive",
    slug: "event-medical-team-lead",
    description: "Leadership training for medics managing onsite coverage at large public events.",
    shortDescription: "Leadership intensive for event medical leads.",
    imageUrl: "/uploads/lms/events/medical-lead.jpg",
    categoryId: "cat-cert",
    categoryName: "Certification",
    eventType: "certification_class",
    deliveryMode: "hybrid",
    instructorName: "Capt. Sam Ortiz",
    instructorUserId: null,
    startsAt: iso(addDays(NOW, 45, 8)),
    endsAt: iso(addDays(NOW, 47, 17)),
    timezone: "America/New_York",
    venueName: "Civic Center Annex",
    venueAddress: "400 Convention Blvd",
    venueCity: "Camden",
    venueState: "NJ",
    venuePostalCode: "08103",
    venueCountry: "US",
    venueLat: 39.9259,
    venueLng: -75.1196,
    onlineMeetingUrl: "https://meet.example.com/med-lead-day2",
    capacity: 40,
    registeredCount: 12,
    seatsRemaining: 28,
    isPublic: true,
    isFree: false,
    priceFrom: 249,
    currency: "USD",
    certificationAvailable: true,
    certificationName: "Event Medical Team Lead",
    requirements: "Minimum 2 years field experience. Pre-read materials will be emailed.",
    cancellationPolicy: "50% refund within 14 days of event.",
    isFeatured: false,
    ageRule: null,
    doorsOpen: null,
    bingoStart: null,
    venueType: null,
    cardsIncluded: null,
    extraCardPrice: null,
    foodAndDrinks: null,
    attire: null,
    linkedCourseId: null,
    linkedLiveSessionId: null,
    revenueTotal: 2988,
  },
  {
    ...baseFields("evt-safety-brief", "completed"),
    title: "Q2 Safety Briefing — Field Operations",
    slug: "q2-safety-briefing",
    description: "Mandatory quarterly safety briefing for all active field staff.",
    shortDescription: "Mandatory quarterly safety briefing.",
    imageUrl: null,
    categoryId: "cat-cert",
    categoryName: "Certification",
    eventType: "safety_briefing",
    deliveryMode: "online",
    instructorName: "Ops Team",
    instructorUserId: null,
    startsAt: iso(addDays(NOW, -30, 10)),
    endsAt: iso(addDays(NOW, -30, 11)),
    timezone: "America/New_York",
    venueName: null,
    venueAddress: null,
    venueCity: null,
    venueState: null,
    venuePostalCode: null,
    venueCountry: null,
    venueLat: null,
    venueLng: null,
    onlineMeetingUrl: "https://meet.example.com/q2-safety",
    capacity: null,
    registeredCount: 86,
    seatsRemaining: null,
    isPublic: false,
    isFree: true,
    priceFrom: 0,
    currency: "USD",
    certificationAvailable: false,
    certificationName: null,
    requirements: null,
    cancellationPolicy: null,
    isFeatured: false,
    ageRule: null,
    doorsOpen: null,
    bingoStart: null,
    venueType: null,
    cardsIncluded: null,
    extraCardPrice: null,
    foodAndDrinks: null,
    attire: null,
    linkedCourseId: null,
    linkedLiveSessionId: null,
    revenueTotal: 0,
  },
];

export const MOCK_LMS_EVENT_TICKETS: LmsEventTicket[] = [
  {
    ...auditFields("tkt-cpr-std"),
    eventId: "evt-cpr-recert",
    name: "Standard seat",
    description: "Includes skills lab and digital card",
    price: 89,
    currency: "USD",
    quantity: 24,
    soldCount: 18,
    saleStartsAt: iso(addDays(NOW, -60)),
    saleEndsAt: iso(addDays(NOW, 13)),
    ticketStatus: "available",
    isFree: false,
    accessRules: null,
  },
  {
    ...auditFields("tkt-med-lead"),
    eventId: "evt-medical-lead",
    name: "Full program",
    description: "Hybrid attendance + certification exam",
    price: 249,
    currency: "USD",
    quantity: 40,
    soldCount: 12,
    saleStartsAt: iso(addDays(NOW, -20)),
    saleEndsAt: iso(addDays(NOW, 44)),
    ticketStatus: "available",
    isFree: false,
    accessRules: null,
  },
  {
    ...auditFields("tkt-bg-free"),
    eventId: "evt-bg-workshop",
    name: "Free registration",
    description: "Online access link sent after signup",
    price: 0,
    currency: "USD",
    quantity: 100,
    soldCount: 42,
    saleStartsAt: null,
    saleEndsAt: null,
    ticketStatus: "available",
    isFree: true,
    accessRules: null,
  },
];

export const MOCK_LMS_EVENT_REGISTRATIONS: LmsEventRegistration[] = [
  {
    ...auditFields("reg-001"),
    eventId: "evt-cpr-recert",
    ticketId: "tkt-cpr-std",
    studentUserId: "1001",
    bookingStatus: "confirmed",
    attendeeName: "Nina Kowalski",
    attendeeEmail: "nina.k@firstaidresponders.net",
    paymentStatus: "paid",
    amountPaid: 89,
    currency: "USD",
    registeredAt: iso(addDays(NOW, -5)),
    checkedInAt: null,
    qrToken: "QR-EVT-CPR-NINA-001",
  },
  {
    ...auditFields("reg-002"),
    eventId: "evt-safety-brief",
    ticketId: "tkt-bg-free",
    studentUserId: "1001",
    bookingStatus: "completed",
    attendeeName: "Nina Kowalski",
    attendeeEmail: "nina.k@firstaidresponders.net",
    paymentStatus: "comped",
    amountPaid: 0,
    currency: "USD",
    registeredAt: iso(addDays(NOW, -45)),
    checkedInAt: iso(addDays(NOW, -30, 10)),
    qrToken: "QR-EVT-SAFETY-NINA-002",
  },
];

export const MOCK_LMS_EVENT_CERTIFICATES: LmsEventCertificate[] = [
  {
    ...auditFields("cert-001"),
    eventId: "evt-safety-brief",
    registrationId: "reg-002",
    studentUserId: "1001",
    studentName: "Nina Kowalski",
    eventTitle: "Q2 Safety Briefing — Field Operations",
    certificateStatus: "issued",
    issuedAt: iso(addDays(NOW, -29)),
    expiresAt: iso(addDays(NOW, 335)),
    renewalRequired: true,
    templateId: "tpl-default",
    downloadUrl: null,
  },
];

export const MOCK_LMS_EVENT_TRANSACTIONS: LmsEventTransaction[] = [
  {
    ...auditFields("txn-001"),
    eventId: "evt-cpr-recert",
    registrationId: "reg-001",
    attendeeName: "Nina Kowalski",
    amount: 89,
    currency: "USD",
    method: "card",
    status: "completed",
    processedAt: iso(addDays(NOW, -5)),
  },
];

export const MOCK_LMS_EVENT_SUPPORT_TICKETS: LmsEventSupportTicket[] = [
  {
    ...auditFields("sup-001"),
    eventId: "evt-cpr-recert",
    registrationId: "reg-001",
    studentUserId: "1001",
    subject: "Need to reschedule CPR lab",
    status: "open",
    priority: "normal",
    lastReplyAt: iso(addDays(NOW, -1)),
  },
];

export const MOCK_LMS_EVENT_NOTIFICATIONS: LmsEventNotification[] = [
  {
    ...auditFields("ntf-001"),
    userId: "1001",
    eventId: "evt-cpr-recert",
    kind: "event_reminder",
    title: "CPR Recertification starts in 14 days",
    body: "Your hands-on lab is scheduled for next month. Review pre-course materials in My Events.",
    readAt: null,
  },
];

export const MOCK_LMS_EVENT_WISHLIST: LmsEventWishlistItem[] = [
  {
    ...auditFields("wish-001"),
    eventId: "evt-medical-lead",
    studentUserId: "1001",
  },
];

export const MOCK_LMS_EVENT_INCOME_REPORT: LmsEventIncomeReport[] = [
  { month: "Jan", grossRevenue: 4200, refunds: 89, netRevenue: 4111, registrationCount: 38 },
  { month: "Feb", grossRevenue: 5100, refunds: 0, netRevenue: 5100, registrationCount: 44 },
  { month: "Mar", grossRevenue: 6300, refunds: 249, netRevenue: 6051, registrationCount: 52 },
  { month: "Apr", grossRevenue: 4800, refunds: 0, netRevenue: 4800, registrationCount: 41 },
  { month: "May", grossRevenue: 7200, refunds: 178, netRevenue: 7022, registrationCount: 58 },
  { month: "Jun", grossRevenue: 1602, refunds: 0, netRevenue: 1602, registrationCount: 18 },
];

export const MOCK_LMS_EVENT_ORGANIZER_KPIS: LmsEventOrganizerKpis = {
  totalEvents: MOCK_LMS_EVENTS.length,
  publishedEvents: MOCK_LMS_EVENTS.filter((e) =>
    ["published", "registration_open", "sold_out", "in_progress"].includes(e.status),
  ).length,
  upcomingEvents: MOCK_LMS_EVENTS.filter((e) => new Date(e.startsAt) > NOW).length,
  totalRegistrations: MOCK_LMS_EVENT_REGISTRATIONS.length + 84,
  attendanceRate: 92,
  totalRevenue: MOCK_LMS_EVENTS.reduce((s, e) => s + e.revenueTotal, 0),
  refunds: 516,
  certificatesIssued: MOCK_LMS_EVENT_CERTIFICATES.length + 12,
  openSupportTickets: MOCK_LMS_EVENT_SUPPORT_TICKETS.filter((t) => t.status === "open").length,
};
