import type { LaunchpadStepId } from "@/lib/launchpad/launchpad-types";

export type LaunchpadStepDef = {
  id: LaunchpadStepId;
  label: string;
  description: string;
  href: string;
  section: "core" | "module";
  moduleLabel?: string;
  required: boolean;
  /** Permission required to see this step (any match). Omit = always visible for company admin. */
  permissions?: string[];
  /** Add-on scope key from addon-scope.ts; omit = no add-on gate */
  addonScope?: string;
};

export const LAUNCHPAD_STEP_DEFS: LaunchpadStepDef[] = [
  {
    id: "verify_email",
    label: "Verify email",
    description: "Verify your email with a one-time code in Email Settings so notifications and invites work reliably.",
    href: "/settings?tab=email#otp-verified",
    section: "core",
    required: true,
    permissions: ["manage-email-settings", "edit-email-settings"],
  },
  {
    id: "brand_settings",
    label: "Brand settings",
    description: "Upload your company logo and favicon (platform defaults are shown until you save your own).",
    href: "/settings?tab=brand",
    section: "core",
    required: true,
    permissions: ["manage-brand-settings", "manage-settings", "edit-settings"],
  },
  {
    id: "company_profile",
    label: "Company profile",
    description: "Add your company name, address, and contact details used on documents.",
    href: "/settings?tab=company",
    section: "core",
    required: true,
    permissions: ["manage-company-settings", "manage-settings", "edit-settings"],
  },
  {
    id: "email_delivery",
    label: "Email delivery",
    description: "Configure SMTP or your email provider so the system can send mail.",
    href: "/settings?tab=email",
    section: "core",
    required: true,
    permissions: ["manage-email-settings", "edit-email-settings"],
  },
  {
    id: "invite_team",
    label: "Invite your team",
    description: "Add staff users and assign roles so others can access modules.",
    href: "/settings?tab=user-management",
    section: "core",
    required: true,
    permissions: ["manage-users", "create-users"],
  },
  {
    id: "notification_templates",
    label: "Notification templates",
    description: "Review email templates for invites, billing, and system alerts.",
    href: "/notification-templates",
    section: "core",
    required: false,
    permissions: ["manage-notification-templates"],
  },
  {
    id: "payment_setup",
    label: "Payment setup",
    description: "Connect bank transfer, Stripe, or PayPal for subscriptions and billing.",
    href: "/settings?tab=payment-settings",
    section: "core",
    required: false,
    permissions: ["manage-settings", "edit-settings"],
  },
  {
    id: "accounting_setup",
    label: "Chart of accounts",
    description: "Set up your chart of accounts or add your first customer.",
    href: "/account/setup",
    section: "module",
    moduleLabel: "Accounting",
    required: false,
    permissions: ["manage-account"],
    addonScope: "account",
  },
  {
    id: "project_first",
    label: "First project",
    description: "Create a project to track tasks, time, and delivery.",
    href: "/projects",
    section: "module",
    moduleLabel: "Projects",
    required: false,
    permissions: ["manage-project"],
    addonScope: "project",
  },
  {
    id: "crm_first_lead",
    label: "First lead",
    description: "Add a lead or deal to start your sales pipeline.",
    href: "/crm/leads",
    section: "module",
    moduleLabel: "CRM",
    required: false,
    permissions: ["manage-leads", "manage-crm"],
    addonScope: "crm",
  },
  {
    id: "hrm_first_employee",
    label: "First employee",
    description: "Add an employee record for HR, payroll, and attendance.",
    href: "/hrm/employees",
    section: "module",
    moduleLabel: "HRM",
    required: false,
    permissions: ["manage-hrm"],
    addonScope: "hrm",
  },
  {
    id: "lms_first_course",
    label: "First course",
    description: "Publish a course for learners in My Learning.",
    href: "/lms/courses",
    section: "module",
    moduleLabel: "LMS",
    required: false,
    permissions: ["manage-lms", "manage-lms-courses"],
    addonScope: "lms",
  },
  {
    id: "expense_workspace",
    label: "Expense workspace",
    description: "Open the expense dashboard to submit reports, lines, and receipts.",
    href: "/expense-management",
    section: "module",
    moduleLabel: "Expense Management",
    required: false,
    permissions: ["manage-expense-management-dashboard"],
    addonScope: "expensemanagement",
  },
  {
    id: "expense_setup",
    label: "Expense categories",
    description: "Configure categories and operations workspace for expense lines.",
    href: "/expense-management/setup",
    section: "module",
    moduleLabel: "Expense Management",
    required: false,
    permissions: ["manage-expense-management"],
    addonScope: "expensemanagement",
  },
  {
    id: "affiliate_partners",
    label: "Affiliate partners",
    description: "Set up your first partner program and referral tracking.",
    href: "/affiliate-business/partners",
    section: "module",
    moduleLabel: "Affiliate Business",
    required: false,
    permissions: ["manage-affiliate-business", "manage-affiliate-partners"],
    addonScope: "affiliatebusiness",
  },
  {
    id: "support_setup",
    label: "Support desk",
    description: "Configure categories, SLA, or your first support ticket.",
    href: "/support-ticket/system-setup/categories",
    section: "module",
    moduleLabel: "Support",
    required: false,
    permissions: ["manage-support-ticket"],
    addonScope: "supportticket",
  },
  {
    id: "storefront_launch",
    label: "Storefront launch",
    description: "Create a website, theme, and products for your online store.",
    href: "/storefront/onboarding",
    section: "module",
    moduleLabel: "Storefront",
    required: false,
    permissions: ["storefront.view", "manage-storefront-settings"],
    addonScope: "storefront",
  },
  {
    id: "pos_catalog",
    label: "POS catalog",
    description: "Add products and open the register for point-of-sale.",
    href: "/products",
    section: "module",
    moduleLabel: "POS",
    required: false,
    permissions: ["view-pos", "manage-pos"],
    addonScope: "pos",
  },
  {
    id: "recruitment_jobs",
    label: "Job postings",
    description: "Post a job and start tracking applicants.",
    href: "/recruitment/job-postings",
    section: "module",
    moduleLabel: "Recruitment",
    required: false,
    permissions: ["manage-recruitment"],
    addonScope: "recruitment",
  },
  {
    id: "appointment_setup",
    label: "Appointment setup",
    description: "Configure business hours and booking options.",
    href: "/appointment/setup",
    section: "module",
    moduleLabel: "Appointment",
    required: false,
    permissions: ["manage-appointment"],
    addonScope: "appointment",
  },
  {
    id: "whatsapp_setup",
    label: "WhatsApp",
    description: "Connect WhatsApp API settings for messaging.",
    href: "/settings?tab=whatsapp-api",
    section: "module",
    moduleLabel: "WhatsApp",
    required: false,
    permissions: ["manage-whatsapp-settings", "manage-whatsapp-chat", "manage-settings", "edit-settings"],
    addonScope: "whatsappchat",
  },
  {
    id: "form_builder_form",
    label: "First form",
    description: "Build a form for HR, onboarding, or data collection.",
    href: "/form-builder",
    section: "module",
    moduleLabel: "Form Builder",
    required: false,
    permissions: ["view-formbuilder-form", "manage-formbuilder-form"],
    addonScope: "formbuilder",
  },
  {
    id: "review_setup",
    label: "Review & test",
    description: "Walk through settings and confirm email, branding, and modules.",
    href: "/settings",
    section: "core",
    required: false,
  },
  {
    id: "go_live",
    label: "Go live",
    description: "Open your dashboard and start working with your team.",
    href: "/dashboard",
    section: "core",
    required: false,
  },
];

export const LAUNCHPAD_QUICK_START_CHIP_LABELS = [
  "Brand",
  "Company",
  "Email",
  "Team",
  "Modules",
] as const;
