/** Event Platform admin route constants. */
export const EVENT_PLATFORM_BASE = "/admin/event-platform";

export const EVENT_PLATFORM_PATHS = {
  dashboard: EVENT_PLATFORM_BASE,
  events: `${EVENT_PLATFORM_BASE}/events`,
  workshops: `${EVENT_PLATFORM_BASE}/workshops`,
  eventDetail: (id: string) => `${EVENT_PLATFORM_BASE}/events/${id}`,
  settings: `${EVENT_PLATFORM_BASE}/settings`,
  vendors: `${EVENT_PLATFORM_BASE}/vendors`,
  vendorDetail: (id: string) => `${EVENT_PLATFORM_BASE}/vendors/${id}`,
  venues: "/admin/venue-management",
  instructors: `${EVENT_PLATFORM_BASE}/instructors`,
  commissions: `${EVENT_PLATFORM_BASE}/commissions`,
  payouts: `${EVENT_PLATFORM_BASE}/payouts`,
  seatmaps: `${EVENT_PLATFORM_BASE}/seatmaps`,
  seatmapNew: `${EVENT_PLATFORM_BASE}/seatmaps/new`,
  seatmapEdit: (id: string) => `${EVENT_PLATFORM_BASE}/seatmaps/${id}/edit`,
  email: `${EVENT_PLATFORM_BASE}/email`,
  emailTemplates: `${EVENT_PLATFORM_BASE}/email/templates`,
  currency: `${EVENT_PLATFORM_BASE}/currency`,
  payments: `${EVENT_PLATFORM_BASE}/payments`,
  paymentsOnline: `${EVENT_PLATFORM_BASE}/payments/online`,
  paymentsOffline: `${EVENT_PLATFORM_BASE}/payments/offline`,
  languages: `${EVENT_PLATFORM_BASE}/languages`,
  translations: `${EVENT_PLATFORM_BASE}/translations`,
  popups: `${EVENT_PLATFORM_BASE}/popups`,
  roles: `${EVENT_PLATFORM_BASE}/roles`,
  adminUsers: `${EVENT_PLATFORM_BASE}/admin-users`,
  integrations: `${EVENT_PLATFORM_BASE}/integrations`,
} as const;
