/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatesRouteImport } from './routes/states'
import { Route as StartBusinessRouteImport } from './routes/start-business'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HostEventRouteImport } from './routes/host-event'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BuyTicketsRouteImport } from './routes/buy-tickets'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as VenueDashboardRouteImport } from './routes/venue.dashboard'
import { Route as PartnerDashboardRouteImport } from './routes/partner.dashboard'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const StartBusinessRoute = StartBusinessRouteImport.update({
  id: '/start-business',
  path: '/start-business',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEventRoute = HostEventRouteImport.update({
  id: '/host-event',
  path: '/host-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTicketsRoute = BuyTicketsRouteImport.update({
  id: '/buy-tickets',
  path: '/buy-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueDashboardRoute = VenueDashboardRouteImport.update({
  id: '/venue/dashboard',
  path: '/venue/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/partner/dashboard',
  path: '/partner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/buy-tickets': typeof BuyTicketsRoute
  '/calendar': typeof CalendarRoute
  '/cities': typeof CitiesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/host-event': typeof HostEventRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/start-business': typeof StartBusinessRoute
  '/states': typeof StatesRoute
  '/terms': typeof TermsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/venue/dashboard': typeof VenueDashboardRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/buy-tickets': typeof BuyTicketsRoute
  '/calendar': typeof CalendarRoute
  '/cities': typeof CitiesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/host-event': typeof HostEventRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/start-business': typeof StartBusinessRoute
  '/states': typeof StatesRoute
  '/terms': typeof TermsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/venue/dashboard': typeof VenueDashboardRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/buy-tickets': typeof BuyTicketsRoute
  '/calendar': typeof CalendarRoute
  '/cities': typeof CitiesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/host-event': typeof HostEventRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/start-business': typeof StartBusinessRoute
  '/states': typeof StatesRoute
  '/terms': typeof TermsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/venue/dashboard': typeof VenueDashboardRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/buy-tickets'
    | '/calendar'
    | '/cities'
    | '/community'
    | '/contact'
    | '/host-event'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/start-business'
    | '/states'
    | '/terms'
    | '/events/$slug'
    | '/partner/dashboard'
    | '/venue/dashboard'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/buy-tickets'
    | '/calendar'
    | '/cities'
    | '/community'
    | '/contact'
    | '/host-event'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/start-business'
    | '/states'
    | '/terms'
    | '/events/$slug'
    | '/partner/dashboard'
    | '/venue/dashboard'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/buy-tickets'
    | '/calendar'
    | '/cities'
    | '/community'
    | '/contact'
    | '/host-event'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/start-business'
    | '/states'
    | '/terms'
    | '/events/$slug'
    | '/partner/dashboard'
    | '/venue/dashboard'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BuyTicketsRoute: typeof BuyTicketsRoute
  CalendarRoute: typeof CalendarRoute
  CitiesRoute: typeof CitiesRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  HostEventRoute: typeof HostEventRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  StartBusinessRoute: typeof StartBusinessRoute
  StatesRoute: typeof StatesRoute
  TermsRoute: typeof TermsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  PartnerDashboardRoute: typeof PartnerDashboardRoute
  VenueDashboardRoute: typeof VenueDashboardRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-business': {
      id: '/start-business'
      path: '/start-business'
      fullPath: '/start-business'
      preLoaderRoute: typeof StartBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-event': {
      id: '/host-event'
      path: '/host-event'
      fullPath: '/host-event'
      preLoaderRoute: typeof HostEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-tickets': {
      id: '/buy-tickets'
      path: '/buy-tickets'
      fullPath: '/buy-tickets'
      preLoaderRoute: typeof BuyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/dashboard': {
      id: '/venue/dashboard'
      path: '/venue/dashboard'
      fullPath: '/venue/dashboard'
      preLoaderRoute: typeof VenueDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/dashboard': {
      id: '/partner/dashboard'
      path: '/partner/dashboard'
      fullPath: '/partner/dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BuyTicketsRoute: BuyTicketsRoute,
  CalendarRoute: CalendarRoute,
  CitiesRoute: CitiesRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  HostEventRoute: HostEventRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  StartBusinessRoute: StartBusinessRoute,
  StatesRoute: StatesRoute,
  TermsRoute: TermsRoute,
  EventsSlugRoute: EventsSlugRoute,
  PartnerDashboardRoute: PartnerDashboardRoute,
  VenueDashboardRoute: VenueDashboardRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
