import {
  BarChart3,
  Bell,
  Box,
  BotMessageSquare,
  Calculator,
  Calendar as CalendarIcon,
  Contact,
  FileText,
  FolderKanban,
  GraduationCap,
  LayoutGrid,
  LayoutDashboard,
  LifeBuoy,
  Map,
  MapPin,
  Route,
  Monitor,
  Receipt,
  Replace,
  Rocket,
  Wallet,
  Settings,
  Handshake,
  Share2,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Tag,
  Store,
  Ticket,
  UserCog,
} from "lucide-react";

import { STOREFRONT_MERCHANT_SECTIONS } from "@/components/storefront/storefront-sections";
import type { NavItem } from "@/types";
import { t } from "@/lib/admin-t";


export const getCompanyMenu = (): NavItem[] => [
  {
    title: t("Launchpad"),
    href: "/launchpad",
    icon: Rocket,
    permission: "manage-dashboard",
    name: "launchpad",
    order: 1,
  },
  {
    title: t("Command Center"),
    href: "/launchpad/command-center",
    icon: LayoutDashboard,
    permission: "manage-dashboard",
    name: "commandcenter",
    order: 2,
  },
  {
    title: t("Dashboard"),
    icon: LayoutGrid,
    permission: "manage-dashboard",
    name: "dashboard",
    order: 3,
    children: [
      { title: t("Project Dashboard"), href: "/project/dashboard", permission: "manage-project-dashboard", dashboardScope: "project" },
      { title: t("Account Dashboard"), href: "/account", permission: "manage-account-dashboard", dashboardScope: "account" },
      {
        title: t("Altitude Dashboard"),
        href: "/storefront/dashboard",
        permission: "manage-storefront-dashboard",
        dashboardScope: "storefront",
      },
      { title: t("HRM Dashboard"), href: "/hrm", permission: "manage-hrm", dashboardScope: "hrm" },
      { title: t("CRM Dashboard"), href: "/crm/dashboard", permission: "manage-crm-dashboard", dashboardScope: "crm" },
      { title: t("POS Dashboard"), href: "/pos/dashboard", permission: "manage-pos-dashboard", dashboardScope: "pos" },
      { title: t("Support Ticket Dashboard"), href: "/support-ticket", permission: "manage-support-ticket-dashboard", dashboardScope: "supportticket" },
      {
        title: t("Expense Management"),
        href: "/expense-management",
        permission: "manage-expense-management-dashboard",
        dashboardScope: "expensemanagement",
      },
      { title: t("LMS Dashboard"), href: "/lms/dashboard", permission: "manage-lms-dashboard", dashboardScope: "lms" },
      {
        title: t("Event Platform Dashboard"),
        href: "/admin/event-platform",
        permission: "reports.view",
        dashboardScope: "eventplatform",
      },
      {
        title: t("Venue Dashboard"),
        href: "/admin/venue-management",
        permission: "venues.view",
        dashboardScope: "venuemanagement",
      },
      {
        title: t("My Learning"),
        href: "/lms/my-learning",
        permission: "view-lms-student-dashboard",
        dashboardScope: "lms",
      },
      {
        title: t("Browse Events"),
        href: "/lms/events",
        permission: "view-lms-student-dashboard",
        dashboardScope: "lms",
      },
      {
        title: t("Affiliate Dashboard"),
        href: "/affiliate-business",
        permission: "manage-affiliate-business-dashboard",
        dashboardScope: "affiliatebusiness",
      },
      {
        title: t("Compliance Dashboard"),
        href: "/compliance",
        permission: "manage-compliance-dashboard",
        dashboardScope: "compliance",
      },
      {
        title: t("Routing Dashboard"),
        href: "/projects/routes",
        permission: "manage-routing-dashboard",
        dashboardScope: "routing",
      },
    ],
  },
  // Accounting menu: just before Media Library (order 2899 < Media Library 2900)
  {
    title: t("Accounting"),
    icon: Calculator,
    permission: "manage-account",
    name: "accounting",
    order: 2899,
    dashboardScope: "account",
    children: [
      { title: t("Accounting"), href: "/account", permission: "manage-account-dashboard" },
      {
        title: t("Finance"),
        permission: "manage-account-dashboard",
        children: [
          { title: t("Dashboard"), href: "/account/finance", permission: "manage-account-dashboard" },
          { title: t("Invoices"), href: "/sales-invoices", permission: "manage-sales-invoices" },
          { title: t("Proposals"), href: "/sales-proposals", permission: "manage-sales-proposals" },
        ],
      },
      {
        title: t("Products"),
        permission: "view-products",
        children: [
          { title: t("Products"), href: "/products", permission: "view-products" },
          { title: t("Categories"), href: "/categories", permission: "view-categories" },
          { title: t("Brands"), href: "/brands", permission: "view-brands" },
          { title: t("Units"), href: "/units", permission: "view-units" },
          { title: t("Taxes"), href: "/taxes", permission: "view-taxes" },
        ],
      },
      {
        title: t("Services"),
        permission: "view-products",
        children: [{ title: t("Services"), href: "/services", permission: "view-products" }],
      },
      { title: t("Customers"), href: "/account/customers", permission: "manage-customers" },
      { title: t("Vendors"), href: "/account/vendors", permission: "manage-vendors" },
      {
        title: t("Banking"),
        permission: "manage-bank-accounts",
        children: [
          { title: t("Bank Accounts"), href: "/account/bank-accounts", permission: "manage-bank-accounts" },
          { title: t("Bank Transactions"), href: "/account/bank-transactions", permission: "manage-bank-transactions" },
          { title: t("Bank Transfers"), href: "/account/bank-transfers", permission: "manage-bank-transfers" },
        ],
      },
      { title: t("Chart Of Accounts"), href: "/account/chart-of-accounts", permission: "manage-chart-of-accounts" },
      { title: t("Vendor Payments"), href: "/account/vendor-payments", permission: "manage-vendor-payments" },
      { title: t("Customer Payments"), href: "/account/customer-payments", permission: "manage-customer-payments" },
      { title: t("Revenue"), href: "/account/revenues", permission: "manage-revenues" },
      { title: t("Expense"), href: "/account/expenses", permission: "manage-expenses" },
      { title: t("Debit Notes"), href: "/account/debit-notes", permission: "manage-debit-notes" },
      { title: t("Credit Notes"), href: "/account/credit-notes", permission: "manage-credit-notes" },
      { title: t("Reports"), href: "/account/reports", permission: "manage-account-reports" },
      { title: t("System Setup"), href: "/account/setup", permission: "manage-account-types" },
    ],
  },
  {
    title: t("Project"),
    icon: FolderKanban,
    permission: "manage-project",
    name: "project",
    order: 5,
    dashboardScope: "project",
    children: [
      { title: t("Dashboard"), href: "/project/dashboard", permission: "manage-project-dashboard" },
      { title: t("Projects"), href: "/projects", permission: "manage-project" },
      {
        title: t("Project Roadmap"),
        permission: "manage-project",
        children: [
          { title: t("Board"), href: "/projects/board", permission: "manage-project" },
        ],
      },
      { title: t("Missions Board"), href: "/projects/missions", permission: "manage-project" },
      { title: t("Projects Report"), href: "/project/report", permission: "manage-project-report" },
      { title: t("My Assignments"), href: "/project/my-assignments" },
      { title: t("System Setup"), href: "/project/setup", permission: "manage-task-stages" },
    ],
  },
  {
    title: t("Routing"),
    icon: Route,
    permission: "manage-routing-dashboard",
    name: "routing",
    order: 52,
    dashboardScope: "routing",
    children: [
      { title: t("My Routes"), href: "/projects/my-routes", permission: "manage-routing-my-routes", icon: Route },
      { title: t("Routes"), href: "/projects/routes", permission: "manage-routing-routes", icon: Route },
      { title: t("FieldMap"), href: "/projects/field-map", permission: "manage-routing-fieldmap", icon: Map },
    ],
  },
  {
    title: t("HRM"),
    icon: UserCog,
    permission: "manage-hrm",
    name: "hrm",
    order: 6,
    dashboardScope: "hrm",
    children: [
      { title: t("Employees"), href: "/hrm/employees", permission: "manage-employees" },
      {
        title: t("Recruitment"),
        permission: "manage-recruitment",
        dashboardScope: "recruitment",
        children: [
          { title: t("Recruitment Dashboard"), href: "/recruitment/dashboard", permission: "manage-recruitment-dashboard" },
          { title: t("Job Locations"), href: "/recruitment/job-locations", permission: "manage-job-locations" },
          { title: t("Custom Questions"), href: "/recruitment/custom-questions", permission: "manage-custom-questions" },
          { title: t("Job Postings"), href: "/recruitment/job-postings", permission: "manage-job-postings" },
          { title: t("Candidates"), href: "/recruitment/candidates", permission: "manage-candidates" },
          { title: t("Interview Rounds"), href: "/recruitment/interview-rounds", permission: "manage-interview-rounds" },
          { title: t("Interviews"), href: "/recruitment/interviews", permission: "manage-interviews" },
          { title: t("Interview Feedback"), href: "/recruitment/interview-feedbacks", permission: "manage-interview-feedbacks" },
          { title: t("Candidate Assessments"), href: "/recruitment/candidate-assessments", permission: "manage-candidate-assessments" },
          { title: t("Offers"), href: "/recruitment/offers", permission: "manage-offers" },
          { title: t("Checklist Items"), href: "/recruitment/checklist-items", permission: "manage-onboarding-checklists" },
          { title: t("Candidate Onboarding"), href: "/recruitment/onboarding", permission: "manage-candidate-onboardings" },
          { title: t("System Setup"), href: "/recruitment/setup", permission: "manage-recruitment-system-setup" },
        ],
      },
      {
        title: t("Appointment"),
        permission: "manage-appointment",
        dashboardScope: "appointment",
        children: [
          { title: t("Appointment Dashboard"), href: "/appointment/dashboard", permission: "manage-appointment-dashboard" },
          { title: t("Appointments"), href: "/appointment/appointments", permission: "manage-appointments" },
          { title: t("Questions"), href: "/appointment/questions", permission: "manage-questions" },
          { title: t("Schedules"), href: "/appointment/schedules", permission: "manage-schedules" },
          { title: t("Appointment Callbacks"), href: "/appointment/callbacks", permission: "manage-appointment-callbacks" },
          { title: t("System Setup"), href: "/appointment/setup", permission: "manage-appointment-hours" },
        ],
      },
      { title: t("Helpdesk"), href: "/helpdesk-tickets", permission: "manage-helpdesk-tickets" },
      {
        title: t("Payslip"),
        permission: "manage-payrolls",
        children: [
          { title: t("Set Salary"), href: "/hrm/set-salary", permission: "manage-set-salary" },
          { title: t("Payroll"), href: "/hrm/payrolls", permission: "manage-payrolls" },
        ],
      },
      {
        title: t("Attendance"),
        permission: "manage-attendances",
        children: [
          { title: t("Shifts"), href: "/hrm/shifts", permission: "manage-shifts" },
          { title: t("Attendances"), href: "/hrm/attendances", permission: "manage-attendances" },
        ],
      },
      {
        title: t("Leave Management"),
        permission: "manage-leave-applications",
        children: [
          { title: t("Leave Types"), href: "/hrm/leave-types", permission: "manage-leave-types" },
          { title: t("Leave Applications"), href: "/hrm/leave-applications", permission: "manage-leave-applications" },
          { title: t("Leave Balance"), href: "/hrm/leave-balance", permission: "manage-leave-balance" },
        ],
      },
      { title: t("Holidays"), href: "/hrm/holidays", permission: "manage-holidays" },
      { title: t("Awards"), href: "/hrm/awards", permission: "manage-awards" },
      { title: t("Promotions"), href: "/hrm/promotions", permission: "manage-promotions" },
      { title: t("Resignations"), href: "/hrm/resignations", permission: "manage-resignations" },
      { title: t("Terminations"), href: "/hrm/terminations", permission: "manage-terminations" },
      { title: t("Warnings"), href: "/hrm/warnings", permission: "manage-warnings" },
      { title: t("Complaints"), href: "/hrm/complaints", permission: "manage-complaints" },
      { title: t("Transfers"), href: "/hrm/transfers", permission: "manage-employee-transfers" },
      { title: t("Documents"), href: "/hrm/documents", permission: "manage-hrm-documents" },
      { title: t("Acknowledgments"), href: "/hrm/acknowledgments", permission: "manage-acknowledgments" },
      { title: t("Announcements"), href: "/hrm/announcements", permission: "manage-announcements" },
      { title: t("Events"), href: "/hrm/events", permission: "manage-events" },
      { title: t("Branches"), href: "/hrm/branches", permission: "manage-branches" },
      { title: t("Departments"), href: "/hrm/departments", permission: "manage-departments" },
      { title: t("Designations"), href: "/hrm/designations", permission: "manage-designations" },
      { title: t("System Setup"), href: "/hrm/setup", permission: "manage-branches" },
    ],
  },
  {
    title: t("CRM"),
    icon: Contact,
    permission: "manage-leads",
    name: "crm",
    order: 7,
    dashboardScope: "crm",
    children: [
      { title: t("Leads"), href: "/crm/leads", permission: "manage-leads" },
      { title: t("Deals"), href: "/crm/deals", permission: "manage-deals" },
      { title: t("System Setup"), href: "/crm/setup", permission: "manage-pipelines" },
      {
        title: t("Reports"),
        permission: "view-reports",
        children: [
          { title: t("Lead Reports"), href: "/crm/reports/leads", permission: "view-reports" },
          { title: t("Deal Reports"), href: "/crm/reports/deals", permission: "view-reports" },
        ],
      },
    ],
  },
  // POS scope items (visible when on /pos/*)
  {
    title: t("POS"),
    icon: Store,
    permission: "view-pos",
    name: "pos",
    order: 100,
    dashboardScope: "pos",
    children: [
      { title: t("Add POS"), href: "/pos", permission: "view-pos" },
      { title: t("POS Orders"), href: "/sales", permission: "view-sales" },
      { title: t("Bank Transfer Requests"), href: "/bank-transfer", permission: "manage-bank-transfer-requests" },
      { title: t("Orders"), href: "/orders", permission: "manage-orders" },
      { title: t("Print Barcode"), href: "/barcode-print", permission: "view-barcode" },
    ],
  },
  {
    title: t("Purchase Management"),
    icon: ShoppingCart,
    permission: "view-purchases",
    order: 200,
    dashboardScope: "pos",
    children: [
      { title: t("Purchases"), href: "/purchases", permission: "view-purchases" },
      { title: t("Purchase Returns"), href: "/purchase-returns", permission: "view-purchase-returns" },
    ],
  },
  {
    title: t("Quotations"),
    href: "/quotations",
    icon: FileText,
    permission: "view-quotations",
    order: 300,
    dashboardScope: "pos",
  },
  {
    title: t("Sales Management"),
    icon: Receipt,
    permission: "view-sales",
    order: 400,
    dashboardScope: "pos",
    children: [
      { title: t("Sales"), href: "/sales", permission: "view-sales" },
      { title: t("Sale Returns"), href: "/sale-returns", permission: "view-sale-returns" },
    ],
  },
  {
    title: t("Reports"),
    icon: BarChart3,
    permission: "view-reports",
    order: 500,
    dashboardScope: "pos",
    children: [
      { title: t("Sales Report"), href: "/reports/sales", permission: "view-reports" },
      { title: t("Purchase Report"), href: "/reports/purchases", permission: "view-reports" },
      { title: t("Expense Report"), href: "/reports/expenses", permission: "view-reports" },
      { title: t("Inventory Report"), href: "/reports/inventory", permission: "view-reports" },
      { title: t("Tax Report"), href: "/reports/tax", permission: "view-reports" },
      { title: t("Customer Report"), href: "/reports/customers", permission: "view-reports" },
      { title: t("Vendor Report"), href: "/reports/vendors", permission: "view-reports" },
      { title: t("Profit & Loss"), href: "/reports/profit-loss", permission: "view-reports" },
      { title: t("Financial Report"), href: "/reports/financial", permission: "view-reports" },
    ],
  },
  {
    title: t("POS Management"),
    icon: Monitor,
    permission: "view-pos",
    order: 700,
    dashboardScope: "pos",
    children: [
      { title: t("Branches"), href: "/branches", permission: "view-branches" },
      { title: t("Cash Registers"), href: "/cash-registers", permission: "view-cash-registers" },
      { title: t("Branch Sales Targets"), href: "/branch-sales-targets", permission: "view-branch-sales-targets" },
      { title: t("POS Sessions"), href: "/pos-sessions", permission: "manage-pos-sessions" },
    ],
  },
  {
    title: t("Contacts"),
    icon: Contact,
    permission: "view-customers",
    order: 800,
    dashboardScope: "pos",
    children: [
      { title: t("Customers"), href: "/customers", permission: "view-customers" },
      { title: t("Vendors"), href: "/vendors", permission: "view-vendors" },
    ],
  },
  {
    title: t("POS expenses"),
    icon: Calculator,
    permission: "view-expenses",
    order: 1000,
    dashboardScope: "pos",
    children: [
      { title: t("Expenses"), href: "/expenses", permission: "view-expenses" },
      { title: t("Expense Categories"), href: "/expense-categories", permission: "view-expense-categories" },
    ],
  },
  {
    title: t("Referral Program"),
    href: "/referral",
    icon: Share2,
    permission: "view-referrals",
    order: 1200,
    dashboardScope: "pos",
  },
  {
    title: t("Calendar"),
    href: "/calendar",
    icon: CalendarIcon,
    permission: "view-calendar",
    order: 1300,
    dashboardScope: "pos",
  },
  {
    title: t("Notification Templates"),
    href: "/notification-templates",
    icon: Bell,
    permission: "manage-notification-templates",
    order: 2920,
  },
  {
    title: t("Expense Management"),
    icon: Wallet,
    permission: "manage-expense-management-dashboard",
    name: "expensemanagement",
    dashboardScope: "expensemanagement",
    order: 2953,
    children: [
      { title: t("Dashboard"), href: "/expense-management", permission: "manage-expense-management-dashboard" },
      { title: t("Operations workspace"), href: "/expense-management/operation-details", permission: "manage-expense-management" },
      { title: t("Reports"), href: "/expense-management/reports", permission: "manage-expense-reports" },
      { title: t("Expenses"), href: "/expense-management/expenses", permission: "manage-expense-entries" },
      { title: t("Receipts"), href: "/expense-management/receipts", permission: "manage-expense-receipts" },
      { title: t("Analytics"), href: "/expense-management/analytics", permission: "manage-expense-analytics" },
      { title: t("System Setup"), href: "/expense-management/setup", permission: "manage-expense-management" },
    ],
  },
  {
    title: t("Support Ticket"),
    icon: LifeBuoy,
    permission: "manage-support-ticket",
    name: "supportticket",
    dashboardScope: "supportticket",
    order: 2955,
    children: [
      { title: t("Dashboard"), href: "/support-ticket", permission: "manage-support-ticket-dashboard" },
      { title: t("Tickets"), href: "/support-ticket/tickets", permission: "manage-tickets" },
      { title: t("Knowledge Base"), href: "/support-ticket/knowledge-base", permission: "manage-knowledge-base" },
      { title: t("FAQ"), href: "/support-ticket/faq", permission: "manage-support-faq" },
      { title: t("Contact"), href: "/support-ticket/contact", permission: "manage-support-contact" },
      { title: t("System Setup"), href: "/support-ticket/system-setup/categories", permission: "manage-support-ticket-settings" },
    ],
  },
  {
    title: t("WhatsApp Chat"),
    icon: BotMessageSquare,
    permission: "manage-whatsapp-chat",
    name: "whatsappchat",
    dashboardScope: "whatsappchat",
    order: 2958,
    children: [
      { title: t("WhatsApp Chat"), href: "/whatsapp-chat", permission: "manage-whatsapp-chat" },
      { title: t("Settings"), href: "/whatsapp-chat/settings", permission: "manage-whatsapp-settings" },
    ],
  },
  {
    title: t("Assets"),
    icon: Box,
    permission: "manage-assets",
    name: "assets",
    dashboardScope: "assets",
    order: 2960,
    children: [
      { title: t("Assets"), href: "/assets", permission: "manage-assets" },
      { title: t("Assignments"), href: "/assets/assignments", permission: "manage-asset-assignments" },
      { title: t("Locations"), href: "/assets/locations", permission: "manage-asset-locations" },
      { title: t("Maintenance"), href: "/assets/maintenance", permission: "manage-asset-maintenance" },
      { title: t("Depreciation"), href: "/assets/depreciation", permission: "manage-asset-depreciation" },
      { title: t("Categories"), href: "/assets/categories", permission: "manage-asset-categories" },
      {
        title: t("Borrow & Rent"),
        permission: "manage-asset-borrow-rent",
        children: [
          { title: t("Borrow & Rent"), href: "/assets/borrow-rent", permission: "manage-asset-borrow-rent" },
          { title: t("Payments"), href: "/assets/borrow-payments", permission: "manage-borrow-payments" },
          { title: t("Report"), href: "/assets/borrow-report", permission: "manage-borrow-report" },
        ],
      },
    ],
  },
  {
    title: t("Coupons"),
    href: "/coupons",
    icon: Tag,
    permission: "manage-coupons",
    order: 2972,
  },
  {
    title: t("Affiliate Business"),
    icon: Handshake,
    permission: "manage-affiliate-business",
    name: "affiliatebusiness",
    order: 2963,
    dashboardScope: "affiliatebusiness",
    children: [
      { title: t("Dashboard"), href: "/affiliate-business", permission: "manage-affiliate-business-dashboard" },
      { title: t("Partners"), href: "/affiliate-business/partners", permission: "manage-affiliate-partners" },
      { title: t("Programs"), href: "/affiliate-business/programs", permission: "manage-affiliate-programs" },
      { title: t("Links"), href: "/affiliate-business/links", permission: "manage-affiliate-links" },
      { title: t("Commissions"), href: "/affiliate-business/commissions", permission: "manage-affiliate-commissions" },
      { title: t("Payouts"), href: "/affiliate-business/payouts", permission: "manage-affiliate-payouts" },
      { title: t("Analytics"), href: "/affiliate-business/analytics", permission: "manage-affiliate-analytics" },
      { title: t("Settings"), href: "/affiliate-business/settings", permission: "manage-affiliate-settings" },
    ],
  },
  {
    title: t("Compliance"),
    icon: ShieldCheck,
    permission: "manage-compliance-dashboard",
    name: "compliance",
    order: 2962,
    dashboardScope: "compliance",
    children: [
      { title: t("Overview"), href: "/compliance", permission: "manage-compliance-dashboard" },
      { title: t("Frameworks"), href: "/compliance/frameworks", permission: "manage-compliance-frameworks" },
      { title: t("Controls"), href: "/compliance/controls", permission: "manage-compliance-controls" },
      { title: t("Evidence"), href: "/compliance/evidence", permission: "manage-compliance-evidence" },
      { title: t("Policies"), href: "/compliance/policies", permission: "manage-compliance-policies" },
      { title: t("Documents"), href: "/compliance/documents", permission: "manage-compliance-documents" },
      { title: t("Monitors"), href: "/compliance/monitors", permission: "manage-compliance-monitors" },
      { title: t("Risks"), href: "/compliance/risks", permission: "manage-compliance-risks" },
      { title: t("Vendors"), href: "/compliance/vendors", permission: "manage-compliance-vendors" },
      { title: t("Access Reviews"), href: "/compliance/access-reviews", permission: "manage-compliance-access-reviews" },
      { title: t("Vulnerabilities"), href: "/compliance/vulnerabilities", permission: "manage-compliance-vulnerabilities" },
      { title: t("Audits"), href: "/compliance/audits", permission: "manage-compliance-audits" },
      { title: t("Trust Center"), href: "/compliance/trust-center", permission: "manage-compliance-trust-center" },
      { title: t("Launchpad"), href: "/compliance/launchpad", permission: "manage-compliance-launchpad" },
      { title: t("Integrations"), href: "/compliance/integrations", permission: "manage-compliance-integrations" },
      { title: t("Tasks"), href: "/compliance/tasks", permission: "manage-compliance-tasks" },
      { title: t("Reports"), href: "/compliance/reports", permission: "manage-compliance-reports" },
      { title: t("Settings"), href: "/compliance/settings", permission: "manage-compliance-settings" },
    ],
  },
  {
    title: t("LMS"),
    icon: GraduationCap,
    permission: "manage-lms",
    name: "lms",
    order: 2964,
    dashboardScope: "lms",
    children: [
      { title: t("My learning"), href: "/lms/my-learning", permission: "view-lms-student-dashboard" },
      { title: t("Browse events"), href: "/lms/events", permission: "view-lms-student-dashboard" },
      { title: t("My events"), href: "/lms/my-events", permission: "view-lms-student-dashboard" },
      { title: t("Event certificates"), href: "/lms/certificates", permission: "view-lms-student-dashboard" },
      { title: t("Training support"), href: "/lms/support", permission: "view-lms-student-dashboard" },
      { title: t("Student dashboard"), href: "/lms/student/dashboard", permission: "manage-lms-student-dashboard" },
      { title: t("Dashboard"), href: "/lms/dashboard", permission: "manage-lms-dashboard" },
      { title: t("Instructor home"), href: "/lms/instructor", permission: "manage-lms-instructor-dashboard" },
      { title: t("My instructor profile"), href: "/lms/instructor/profile", permission: "manage-lms-instructor-profile" },
      { title: t("My courses"), href: "/lms/instructor/courses", permission: "view-lms-instructor-assignments" },
      { title: t("Courses"), href: "/lms/courses", permission: "manage-lms-courses" },
      { title: t("Classes"), href: "/lms/classes", permission: "manage-lms-classes" },
      { title: t("Students"), href: "/lms/students", permission: "manage-lms-students" },
      { title: t("Instructors"), href: "/lms/instructors", permission: "manage-lms-instructors" },
      { title: t("Meetings"), href: "/lms/meetings", permission: "manage-lms-meetings" },
      { title: t("Analytics"), href: "/lms/analytics", permission: "manage-lms-analytics" },
      { title: t("Settings"), href: "/lms/settings", permission: "manage-lms-settings" },
    ],
  },
  {
    title: t("Venue Management"),
    icon: MapPin,
    permission: "manage-venue-management-dashboard",
    name: "venue-management",
    order: 2964,
    dashboardScope: "venuemanagement",
    children: [
      {
        title: t("Venues"),
        href: "/admin/venue-management",
        permission: "venues.view",
        name: "venue-management-venues",
      },
      { title: t("Venue Categories"), href: "/admin/venue-management/categories", permission: "venues.manage" },
      { title: t("Venue Types"), href: "/admin/venue-management/types", permission: "venues.manage" },
    ],
  },
  {
    title: t("Event Platform"),
    icon: Ticket,
    permission: "manage-event-platform",
    name: "event-platform",
    order: 2965,
    dashboardScope: "eventplatform",
    children: [
      { title: t("Dashboard"), href: "/admin/event-platform", permission: "reports.view" },
      { title: t("Bingo Events"), href: "/admin/event-platform/events", permission: "manage-lms-events" },
      { title: t("Workshops"), href: "/admin/event-platform/workshops", permission: "manage-lms-events" },
      { title: t("Vendors"), href: "/admin/event-platform/vendors", permission: "vendors.view" },
      { title: t("Hosts"), href: "/admin/event-platform/hosts", permission: "hosts.view" },
      { title: t("Sponsors"), href: "/admin/event-platform/sponsors", permission: "sponsors.view" },
      { title: t("Bingo Games"), href: "/admin/event-platform/bingo-games", permission: "bingoGames.view" },
      { title: t("Event FAQs"), href: "/admin/event-platform/event-faqs", permission: "eventFaqs.view" },
      { title: t("Commission"), href: "/admin/event-platform/commissions", permission: "commissions.manage" },
      { title: t("Payouts"), href: "/admin/event-platform/payouts", permission: "payouts.manage" },
      { title: t("Seat Maps"), href: "/admin/event-platform/seatmaps", permission: "cms.manage" },
      { title: t("Settings"), href: "/admin/event-platform/settings", permission: "settings.manage" },
    ],
  },
  {
    title: t("Marketplace"),
    icon: Store,
    permission: "marketplace.view",
    name: "marketplace",
    dashboardScope: "marketplace",
    order: 2966,
    children: [
      { title: t("Marketplace"), href: "/company/marketplace", permission: "marketplace.view" },
      { title: t("My Orders"), href: "/company/orders", permission: "marketplace.orders.view" },
      { title: t("Delivery Status"), href: "/company/delivery-status", permission: "marketplace.view" },
    ],
  },
  {
    title: t("Storefronts"),
    icon: ShoppingBag,
    permission: "storefront.view",
    name: "storefront",
    dashboardScope: "storefront",
    order: 2968,
    children: STOREFRONT_MERCHANT_SECTIONS.map((s) => ({
      name: s.id,
      title: t(s.title),
      href: s.href,
      permission: s.permission,
    })),
  },
  {
    title: t("Resume Builder"),
    href: "/resume-builder",
    icon: FileText,
    permission: "manage-resume-builder",
    name: "resumebuilder",
    dashboardScope: "resumebuilder",
    order: 515,
    children: [
      { title: t("Resumes"), href: "/resume-builder/resumes", permission: "view-resumes" },
      { title: t("System Setup"), href: "/resume-builder/system-setup", permission: "manage-resume-builder-settings" },
    ],
  },
  {
    title: t("Settings"),
    href: "/settings",
    icon: Settings,
    permission: "manage-settings",
    order: 3000,
  },
];

