import {
  Bell,
  Bot,
  Boxes,
  Crown,
  Handshake,
  Headphones,
  Image,
  Layout,
  LayoutGrid,
  Link2,
  Mail,
  Package,
  Receipt,
  Settings,
  ShoppingCart,
  Store,
  Tag,
  Users,
} from "lucide-react";

import type { NavItem } from "@/types";
import { t } from "@/lib/admin-t";


export const getSuperAdminMenu = (): NavItem[] => [
  {
    title: t("Dashboard"),
    href: "/dashboard",
    icon: LayoutGrid,
    permission: "manage-dashboard",
    order: 1,
  },
  {
    title: t("Companies"),
    href: "/companies",
    icon: Users,
    permission: "manage-users",
    order: 20,
  },
  {
    title: t("Partnerships"),
    icon: Handshake,
    permission: "manage-partnerships",
    order: 24,
    children: [
      { title: t("Overview"), href: "/partnerships", permission: "manage-partnerships", order: 1 },
      { title: t("Brands"), href: "/partnerships/brands", permission: "manage-brand-ownership", order: 2 },
      { title: t("Partners"), href: "/partnerships/partners", permission: "manage-brand-ownership", order: 3 },
      {
        title: t("Ownership Requests"),
        href: "/partnerships/ownership-requests",
        permission: "manage-brand-ownership",
        order: 4,
      },
      {
        title: t("Ownership History"),
        href: "/partnerships/ownership-history",
        permission: "manage-brand-ownership",
        order: 5,
      },
      { title: t("Partner Applications"), href: "/partnerships/applications", permission: "manage-partnerships", order: 6 },
      { title: t("Referral Links"), href: "/partnerships/referral-links", permission: "manage-partnerships", order: 7 },
      { title: t("Commission Rules"), href: "/partnerships/commission-rules", permission: "manage-partnerships", order: 8 },
      { title: t("Payouts"), href: "/partnerships/payouts", permission: "manage-partnerships", order: 9 },
      { title: t("Marketing Pages"), href: "/partnerships/marketing-pages", permission: "manage-partnerships", order: 10 },
    ],
  },
  {
    title: t("Marketplace"),
    icon: Store,
    permission: "marketplace.view",
    order: 26,
    children: [
      { title: t("Marketplace Dashboard"), href: "/marketplace/admin", permission: "marketplace.view", order: 1 },
      { title: t("Vendors"), href: "/marketplace/admin/vendors", permission: "marketplace.vendor.view", order: 2 },
      { title: t("Products"), href: "/marketplace/admin/products", permission: "marketplace.vendor.view", order: 3 },
      { title: t("Orders"), href: "/marketplace/admin/orders", permission: "marketplace.orders.view", order: 4 },
      {
        title: t("Delivery Map"),
        href: "/admin/marketplace/delivery-map",
        permission: "marketplace.delivery_queue.view",
        order: 5,
      },
      {
        title: t("Delivery Queue"),
        href: "/admin/marketplace/delivery-queue",
        permission: "marketplace.delivery_queue.view",
        order: 6,
      },
      {
        title: t("Delivery Events"),
        href: "/admin/marketplace/delivery-events",
        permission: "marketplace.delivery_queue.view",
        order: 7,
      },
      { title: t("Settings"), href: "/marketplace/admin/settings", permission: "marketplace.settings.manage", order: 8 },
    ],
  },
  {
    title: t("Memberships"),
    href: "/memberships/manage",
    icon: Crown,
    permission: "manage-landing-page",
    order: 2810,
  },
  {
    title: t("Store"),
    icon: ShoppingCart,
    permission: "storefront.view",
    order: 2820,
    children: [
      { title: t("Products"), href: "/storefront/products", permission: "storefront.view", order: 1 },
      { title: t("Categories"), href: "/storefront/collections", permission: "storefront.view", order: 2 },
      { title: t("Orders"), href: "/storefront/orders", permission: "storefront.view", order: 3 },
    ],
  },
  {
    title: t("Helpdesk"),
    icon: Headphones,
    permission: "manage-helpdesk-tickets",
    order: 2822,
    children: [
      // Match Laravel: access is gated by manage-helpdesk-tickets + manage-any/manage-own.
      { title: t("Tickets"), href: "/helpdesk-tickets", permission: "manage-helpdesk-tickets" },
      { title: t("Categories"), href: "/helpdesk-categories", permission: "manage-helpdesk-categories" },
    ],
  },
  {
    title: t("CMS"),
    href: "/cms/waterice-landing",
    icon: Layout,
    permission: "manage-landing-page",
    order: 2825,
    children: [
      { title: t("Water Ice Landing"), href: "/cms/waterice-landing", permission: "manage-landing-page", order: 1 },
      { title: t("Custom Pages"), href: "/custom-pages", permission: "manage-custom-pages", order: 3 },
      {
        title: t("Newsletter Subscribers"),
        href: "/newsletter-subscribers",
        permission: "manage-newsletter-subscribers",
        order: 4,
      },
    ],
  },
  {
    title: t("Email Templates"),
    href: "/email-templates",
    icon: Mail,
    permission: "manage-email-templates",
    order: 2850,
  },
  {
    title: t("Notification Templates"),
    href: "/notification-templates",
    icon: Bell,
    permission: "manage-notification-templates",
    order: 2900,
  },
  {
    title: t("Media Library"),
    href: "/media-library",
    icon: Image,
    permission: "manage-media",
    order: 2950,
  },
  {
    title: t("Industry Modules"),
    href: "/business-modules",
    icon: Boxes,
    permission: "manage-modules",
    order: 2975,
  },
  {
    title: t("Autopilot Modules"),
    href: "/autopilot-modules",
    icon: Bot,
    permission: "manage-modules",
    order: 2987,
  },
  {
    title: t("Features"),
    href: "/add-ons",
    icon: Package,
    permission: "manage-add-on",
    order: 3000,
  },
  {
    title: t("Resources"),
    href: "/resources",
    icon: Link2,
    permission: "manage-dashboard",
    order: 3040,
  },
  {
    title: t("Settings"),
    href: "/settings",
    icon: Settings,
    permission: "manage-settings",
    order: 3050,
  },
];

