-- Event financials: expenses, manual revenue, financial lock

CREATE TABLE IF NOT EXISTS `event_revenue_entries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT NOT NULL,
  `event_id` BIGINT NOT NULL,
  `category` VARCHAR(64) NOT NULL,
  `payee_name` VARCHAR(255) NULL,
  `description` VARCHAR(512) NULL,
  `amount` DECIMAL(12, 2) NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'USD',
  `payment_status` VARCHAR(32) NOT NULL DEFAULT 'paid',
  `received_at` DATETIME(3) NULL,
  `source_type` VARCHAR(64) NULL,
  `source_id` VARCHAR(128) NULL,
  `notes` TEXT NULL,
  `created_by_id` BIGINT NULL,
  `updated_by_id` BIGINT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `event_revenue_entries_organization_id_event_id_idx` (`organization_id`, `event_id`),
  INDEX `event_revenue_entries_source_idx` (`organization_id`, `event_id`, `source_type`, `source_id`),
  CONSTRAINT `event_revenue_entries_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_revenue_entries_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `lms_events`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_revenue_entries_created_by_id_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_expenses` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT NOT NULL,
  `event_id` BIGINT NOT NULL,
  `category` VARCHAR(64) NOT NULL,
  `payee_type` VARCHAR(32) NULL,
  `payee_id` BIGINT NULL,
  `payee_name` VARCHAR(255) NULL,
  `description` VARCHAR(512) NULL,
  `quantity` DECIMAL(12, 4) NOT NULL DEFAULT 1,
  `unit_cost` DECIMAL(12, 2) NOT NULL DEFAULT 0,
  `subtotal` DECIMAL(12, 2) NOT NULL DEFAULT 0,
  `tax` DECIMAL(12, 2) NOT NULL DEFAULT 0,
  `total` DECIMAL(12, 2) NOT NULL DEFAULT 0,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'USD',
  `payment_status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `due_date` DATETIME(3) NULL,
  `paid_at` DATETIME(3) NULL,
  `receipt_url` VARCHAR(2048) NULL,
  `accounting_expense_id` BIGINT NULL,
  `source_type` VARCHAR(64) NULL,
  `source_id` VARCHAR(128) NULL,
  `notes` TEXT NULL,
  `created_by_id` BIGINT NULL,
  `approved_by_id` BIGINT NULL,
  `updated_by_id` BIGINT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `event_expenses_organization_id_event_id_idx` (`organization_id`, `event_id`),
  INDEX `event_expenses_category_idx` (`organization_id`, `event_id`, `category`),
  INDEX `event_expenses_source_idx` (`organization_id`, `event_id`, `source_type`, `source_id`),
  CONSTRAINT `event_expenses_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_expenses_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `lms_events`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_expenses_created_by_id_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `event_expenses_approved_by_id_fkey` FOREIGN KEY (`approved_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_financial_locks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT NOT NULL,
  `event_id` BIGINT NOT NULL,
  `locked` BOOLEAN NOT NULL DEFAULT false,
  `locked_at` DATETIME(3) NULL,
  `locked_by_id` BIGINT NULL,
  `unlocked_at` DATETIME(3) NULL,
  `notes` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `event_financial_locks_event_id_key` (`event_id`),
  INDEX `event_financial_locks_organization_id_event_id_idx` (`organization_id`, `event_id`),
  CONSTRAINT `event_financial_locks_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_financial_locks_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `lms_events`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_financial_locks_locked_by_id_fkey` FOREIGN KEY (`locked_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
