import type {
  CompanyThemeCustomizerField,
  CompanyThemeCustomizerPanel,
} from "@/lib/company-themes/customizer-schema";

export const GLOBAL_PAGE = "*";
export const CRIMSON_HOME = "/";

export const CRIMSON_PANELS: CompanyThemeCustomizerPanel[] = [
  {
    id: "site-identity",
    label: "Site identity",
    page: GLOBAL_PAGE,
    order: 10,
    description: "Website logo, favicon, and browser title (independent from dashboard Brand Settings).",
  },
  { id: "colors", label: "Colors", page: GLOBAL_PAGE, order: 20, description: "Brand colors applied across the site." },
  { id: "hero", label: "Hero slider", page: CRIMSON_HOME, order: 30, description: "Slide backgrounds, text, and buttons." },
  { id: "who-we-are", label: "Who we are", page: CRIMSON_HOME, order: 40 },
  { id: "service-boxes", label: "What we do (service boxes)", page: CRIMSON_HOME, order: 50 },
  { id: "top-banner", label: "Top banner", page: CRIMSON_HOME, order: 60 },
  { id: "veterans", label: "Founded by veterans", page: CRIMSON_HOME, order: 70 },
  { id: "professional-security", label: "Professional security", page: CRIMSON_HOME, order: 80 },
  { id: "stats-security", label: "Stats & security", page: CRIMSON_HOME, order: 90 },
  { id: "demo-video", label: "Demo video", page: CRIMSON_HOME, order: 100 },
  { id: "counters", label: "Achievement counters", page: CRIMSON_HOME, order: 110 },
  { id: "team", label: "Team", page: CRIMSON_HOME, order: 120 },
  { id: "testimonials", label: "Testimonials", page: CRIMSON_HOME, order: 130 },
  { id: "news-blog", label: "News & blog", page: CRIMSON_HOME, order: 140 },
  { id: "about-page", label: "Page header", page: "/about-us", order: 10 },
  { id: "contact-page", label: "Page header", page: "/contact-us", order: 10 },
  { id: "careers-page", label: "Page header", page: "/careers", order: 10 },
];

function boxFields(
  prefix: string,
  panelId: string,
  widgetId: string,
  defaults: { heading: string; title: string; desc: string; btn: string },
): CompanyThemeCustomizerField[] {
  return [
    {
      id: `${prefix}.heading`,
      label: "Eyebrow heading",
      panelId,
      page: CRIMSON_HOME,
      type: "text",
      target: { kind: "widget-class", widgetId, className: "dsvy-element-heading", tag: "h4" },
      defaultValue: defaults.heading,
    },
    {
      id: `${prefix}.title`,
      label: "Title",
      panelId,
      page: CRIMSON_HOME,
      type: "text",
      target: { kind: "widget-class", widgetId, className: "dsvy-element-title", tag: "h2" },
      defaultValue: defaults.title,
    },
    {
      id: `${prefix}.description`,
      label: "Description",
      panelId,
      page: CRIMSON_HOME,
      type: "textarea",
      target: { kind: "widget-class", widgetId, className: "dsvy-heading-desc", tag: "div" },
      defaultValue: defaults.desc,
    },
    {
      id: `${prefix}.button`,
      label: "Button label",
      panelId,
      page: CRIMSON_HOME,
      type: "text",
      target: { kind: "widget-ihbox-btn", widgetId },
      defaultValue: defaults.btn,
    },
  ];
}

function counterFields(
  prefix: string,
  widgetId: string,
  number: string,
  label: string,
): CompanyThemeCustomizerField[] {
  return [
    {
      id: `${prefix}.number`,
      label: "Counter value",
      panelId: "counters",
      page: CRIMSON_HOME,
      type: "text",
      target: { kind: "widget-fid-number", widgetId },
      defaultValue: number,
    },
    {
      id: `${prefix}.label`,
      label: "Counter label",
      panelId: "counters",
      page: CRIMSON_HOME,
      type: "text",
      target: { kind: "widget-fid-label", widgetId },
      defaultValue: label,
    },
  ];
}

export const CRIMSON_FIELDS: CompanyThemeCustomizerField[] = [
  {
    id: "website.logoMain",
    label: "Site logo",
    panelId: "site-identity",
    page: GLOBAL_PAGE,
    type: "image",
    target: { kind: "site-logo-main" },
    defaultValue: "/content/uploads/sites/3/2022/06/crimson-logo-white.png",
    helpText: "Public website only (header and footer). Does not change the SecurX dashboard logo.",
  },
  {
    id: "website.logoSticky",
    label: "Sticky header logo",
    panelId: "site-identity",
    page: GLOBAL_PAGE,
    type: "image",
    target: { kind: "site-logo-sticky" },
    defaultValue: "/content/uploads/sites/3/2022/06/crimson-logo-dark.png",
    helpText: "Public website only — shown when the header sticks on scroll.",
  },
  {
    id: "website.favicon",
    label: "Favicon",
    panelId: "site-identity",
    page: GLOBAL_PAGE,
    type: "image",
    target: { kind: "site-favicon" },
    defaultValue: "/content/uploads/sites/3/2020/06/crimson-favicon.png",
    helpText: "Public website browser tab icon only. Dashboard favicon is set under Brand Settings.",
  },
  {
    id: "global.siteTitle",
    label: "Browser tab title (home)",
    panelId: "site-identity",
    page: GLOBAL_PAGE,
    type: "text",
    target: { kind: "document-title", page: CRIMSON_HOME },
    defaultValue: "Crimson Consulting",
  },
  {
    id: "global.primaryColor",
    label: "Primary accent color",
    panelId: "colors",
    page: GLOBAL_PAGE,
    type: "color",
    target: { kind: "css-var", variable: "--pf-company-primary" },
    defaultValue: "#c01120",
    helpText: "Used for buttons, highlights, and accent areas.",
  },
  {
    id: "global.secondaryColor",
    label: "Secondary color",
    panelId: "colors",
    page: GLOBAL_PAGE,
    type: "color",
    target: { kind: "css-var", variable: "--pf-company-secondary" },
    defaultValue: "#0a1628",
    helpText: "Used for dark backgrounds, header, and footer areas.",
  },
  {
    id: "home.hero.slide1Image",
    label: "Slide 1 background image",
    panelId: "hero",
    page: CRIMSON_HOME,
    type: "image",
    target: { kind: "slider-slide-image", slideKey: "rs-1" },
    defaultValue: "/content/uploads/sites/3/2020/06/slider-02-a.jpg",
    helpText: "Recommended: 1920×950px or wider. First slide in the carousel.",
  },
  {
    id: "home.hero.slide2Image",
    label: "Slide 2 background image",
    panelId: "hero",
    page: CRIMSON_HOME,
    type: "image",
    target: { kind: "slider-slide-image", slideKey: "rs-3" },
    defaultValue: "/content/uploads/sites/3/2020/06/new-slider-02-b.jpg",
    helpText: "Recommended: 1920×950px or wider. Second slide in the carousel.",
  },
  {
    id: "home.hero.outline",
    label: "Hero outline text",
    panelId: "hero",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "element-id", elementId: "slider-1-slide-1-layer-8" },
    defaultValue: "Security service",
  },
  {
    id: "home.hero.headlineLeft",
    label: "Hero headline (left)",
    panelId: "hero",
    page: CRIMSON_HOME,
    type: "textarea",
    target: { kind: "element-id", elementId: "slider-1-slide-1-layer-0" },
    defaultValue: "for your <br />safety",
  },
  {
    id: "home.hero.headlineRight",
    label: "Hero headline (right highlight)",
    panelId: "hero",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "element-id", elementId: "slider-1-slide-1-layer-15" },
    defaultValue: "personal",
  },
  {
    id: "home.hero.watermark",
    label: "Hero background watermark text",
    panelId: "hero",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "element-id", elementId: "slider-1-slide-1-layer-11" },
    defaultValue: "Security",
  },
  {
    id: "home.hero.ctaPrimary",
    label: "Hero primary button",
    panelId: "hero",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "element-id", elementId: "slider-1-slide-3-layer-16" },
    defaultValue: "Readmore",
  },
  {
    id: "home.hero.ctaSecondary",
    label: "Hero secondary button",
    panelId: "hero",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "element-id", elementId: "slider-1-slide-3-layer-18" },
    defaultValue: "Contact us",
  },
  {
    id: "home.whoWeAre.subtitle",
    label: "Section label",
    panelId: "who-we-are",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget-class", widgetId: "1e360db3", className: "dsvy-element-subtitle", tag: "h4" },
    defaultValue: "Who we are",
  },
  {
    id: "home.whoWeAre.title",
    label: "Section heading",
    panelId: "who-we-are",
    page: CRIMSON_HOME,
    type: "textarea",
    target: { kind: "widget-class", widgetId: "1e360db3", className: "dsvy-element-title", tag: "h2" },
    defaultValue: "When you need better security installation",
  },
  {
    id: "home.whoWeAre.body",
    label: "Section description",
    panelId: "who-we-are",
    page: CRIMSON_HOME,
    type: "textarea",
    target: { kind: "widget", widgetId: "cf57d89", tag: "p" },
    defaultValue:
      "Our еxреrіеnсеd ѕесurіtу guards provide you thе rіght ѕесurіtу ѕоlutіоnѕ thаt уоu nееdѕ. Give best ѕесurіtу ѕуѕtеmѕ and wе еnѕurе thаt уоu аrе ѕаfе in any hаrm and attacks.",
  },
  ...boxFields("home.box1", "service-boxes", "506ddf9b", {
    heading: "Responding to Attack",
    title: "Trustworthy Expert",
    desc: "We provide best security solutions including Guard services & mobile patrols",
    btn: "Get Expert",
  }),
  ...boxFields("home.box2", "service-boxes", "7fddea5d", {
    heading: "Explore the Technique",
    title: "Bodyguard Security",
    desc: "We provide best security solutions including Guard services & mobile patrols",
    btn: "Get Safety",
  }),
  ...boxFields("home.box3", "service-boxes", "54b7533e", {
    heading: "Explore the Features",
    title: "Self Motivated Guard",
    desc: "We provide best security solutions including Guard services & mobile patrols",
    btn: "Get Guard",
  }),
  {
    id: "home.banner.title",
    label: "Banner heading",
    panelId: "top-banner",
    page: CRIMSON_HOME,
    type: "textarea",
    target: { kind: "widget", widgetId: "154827cf", tag: "h2" },
    defaultValue: "STANDING OFFICERS FOR <br /> EVERY SITUATION",
  },
  {
    id: "home.banner.phone",
    label: "Banner phone number",
    panelId: "top-banner",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget", widgetId: "4c8befed", tag: "h2" },
    defaultValue: "1-800-888-9999",
  },
  {
    id: "home.banner.cta",
    label: "Banner button label",
    panelId: "top-banner",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget-button", widgetId: "602a9e24" },
    defaultValue: "Get Guard",
  },
  {
    id: "home.veterans.title",
    label: "Main heading",
    panelId: "veterans",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "text-replace", search: "Founded by Veterans" },
    defaultValue: "Founded by Veterans",
  },
  {
    id: "home.veterans.subtitle",
    label: "Subheading",
    panelId: "veterans",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "text-replace", search: "Our Staff Knows What It Is To Serve" },
    defaultValue: "Our Staff Knows What It Is To Serve",
  },
  {
    id: "home.proSecurity.subtitle",
    label: "Section label",
    panelId: "professional-security",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget-class", widgetId: "67d483b1", className: "dsvy-element-subtitle", tag: "h4" },
    defaultValue: "Our Security",
  },
  {
    id: "home.proSecurity.title",
    label: "Section heading",
    panelId: "professional-security",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget-class", widgetId: "67d483b1", className: "dsvy-element-title", tag: "h2" },
    defaultValue: "Professional Security",
  },
  {
    id: "home.stats.title",
    label: "Stats heading",
    panelId: "stats-security",
    page: CRIMSON_HOME,
    type: "textarea",
    target: { kind: "widget", widgetId: "6c0bf031", tag: "h2" },
    defaultValue: "We perform over <span>400 Successful</span><br /> Security every year",
  },
  {
    id: "home.stats.subtitle",
    label: "Stats subtitle",
    panelId: "stats-security",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget", widgetId: "2bc3f493", tag: "h2" },
    defaultValue: "Effective integrated security",
  },
  {
    id: "home.stats.body",
    label: "Stats description",
    panelId: "stats-security",
    page: CRIMSON_HOME,
    type: "textarea",
    target: { kind: "widget", widgetId: "4dc2415d", tag: "p" },
    defaultValue:
      "Get best security from a caring and professionals bodyguards. Our solution are cost effective аnd we are the еnѕurіng thаt you and уоur ѕtаff аrе рrоtесt аgаіnѕt an аttасk.",
  },
  {
    id: "home.video.title",
    label: "Video section title",
    panelId: "demo-video",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget", widgetId: "7a7af822", tag: "h2" },
    defaultValue: "Watch Our Demo Video",
  },
  {
    id: "home.video.subtitle",
    label: "Video section subtitle",
    panelId: "demo-video",
    page: CRIMSON_HOME,
    type: "textarea",
    target: { kind: "widget", widgetId: "b2cd7be", tag: "div" },
    defaultValue: "Play this video and see our company's guards security.",
  },
  ...counterFields("home.counter1", "5721f6cf", "450", "Objects protected"),
  ...counterFields("home.counter2", "75d5afed", "125", "Cameras Installed"),
  ...counterFields("home.counter3", "3e1c4229", "235", "Professionals"),
  ...counterFields("home.counter4", "61852e66", "360", "Qualified Staff"),
  {
    id: "home.team.subtitle",
    label: "Section label",
    panelId: "team",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget-class", widgetId: "3ef37d84", className: "dsvy-element-subtitle", tag: "h4" },
    defaultValue: "Security Experts",
  },
  {
    id: "home.team.title",
    label: "Section heading",
    panelId: "team",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget-class", widgetId: "3ef37d84", className: "dsvy-element-title", tag: "h2" },
    defaultValue: "Meet Our Bodyguards",
  },
  {
    id: "home.testimonials.subtitle",
    label: "Section label",
    panelId: "testimonials",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget-class", widgetId: "179367e1", className: "dsvy-element-subtitle", tag: "h4" },
    defaultValue: "Testimonials",
  },
  {
    id: "home.testimonials.title",
    label: "Section heading",
    panelId: "testimonials",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget-class", widgetId: "179367e1", className: "dsvy-element-title", tag: "h2" },
    defaultValue: "WHAT OUR CLIENTS SAY ABOUT US",
  },
  {
    id: "home.testimonials.cta",
    label: "Read more button",
    panelId: "testimonials",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget-button", widgetId: "2c478b96" },
    defaultValue: "Read More",
  },
  {
    id: "home.blog.subtitle",
    label: "Section label",
    panelId: "news-blog",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget-class", widgetId: "156f026b", className: "dsvy-element-subtitle", tag: "h4" },
    defaultValue: "Security Advice's",
  },
  {
    id: "home.blog.title",
    label: "Section heading",
    panelId: "news-blog",
    page: CRIMSON_HOME,
    type: "text",
    target: { kind: "widget-class", widgetId: "156f026b", className: "dsvy-element-title", tag: "h2" },
    defaultValue: "Latest News &amp; Blog",
  },
  {
    id: "about.pageTitle",
    label: "Page title",
    panelId: "about-page",
    page: "/about-us",
    type: "text",
    target: { kind: "css-selector", selector: "h1.dsvy-tbar-title" },
    defaultValue: "About Crimson Consulting",
  },
  {
    id: "about.browserTitle",
    label: "Browser tab title",
    panelId: "about-page",
    page: "/about-us",
    type: "text",
    target: { kind: "document-title", page: "/about-us" },
    defaultValue: "About Us - Crimson Consulting Security",
  },
  {
    id: "contact.pageTitle",
    label: "Page title",
    panelId: "contact-page",
    page: "/contact-us",
    type: "text",
    target: { kind: "css-selector", selector: "h1.dsvy-tbar-title" },
    defaultValue: "Contact Us",
  },
  {
    id: "contact.browserTitle",
    label: "Browser tab title",
    panelId: "contact-page",
    page: "/contact-us",
    type: "text",
    target: { kind: "document-title", page: "/contact-us" },
    defaultValue: "Contact Us - Crimson Consulting Security",
  },
  {
    id: "contact.formLabel",
    label: "Form section label",
    panelId: "contact-page",
    page: "/contact-us",
    type: "text",
    target: {
      kind: "scoped-inner",
      scopeClass: "contact-form-wrapper",
      tag: "span",
      innerClass: "section-label",
    },
    defaultValue: "Contact Us",
    helpText: "Small label above the contact form.",
  },
  {
    id: "contact.infoLabel",
    label: "Info section label",
    panelId: "contact-page",
    page: "/contact-us",
    type: "text",
    target: {
      kind: "scoped-inner",
      scopeClass: "contact-info-wrapper",
      tag: "span",
      innerClass: "section-label",
    },
    defaultValue: "Information",
  },
  {
    id: "careers.pageTitle",
    label: "Page title",
    panelId: "careers-page",
    page: "/careers",
    type: "text",
    target: { kind: "text-replace", search: "Join Our Team" },
    defaultValue: "Join Our Team",
  },
  {
    id: "careers.browserTitle",
    label: "Browser tab title",
    panelId: "careers-page",
    page: "/careers",
    type: "text",
    target: { kind: "document-title", page: "/careers" },
    defaultValue: "Careers - Join Our Team | Crimson Consulting",
  },
];
