import { describe, expect, it } from "vitest";

import { buildDefaultSowContent, mergeSowWithDefaults, renderSowHtml } from "@/lib/project-sow";
import { buildWorkPeriodLabelFromDates, renderSowDocumentHtml } from "@/lib/project-sow-document";
import {
  buildDefaultSowFormData,
  formDataToSowRecord,
  formatGanttLocationLine,
  mergeSowFormData,
  parseFormDataJson,
  sowRecordToFormHints,
} from "@/lib/project-sow-form";

const projectMeta = {
  name: "Super Bowl",
  property_name: "Allegiant Stadium",
  address: "3333 Al Davis Way",
  address_2: null as string | null,
  city: "Las Vegas",
  state: "NV",
  zip_code: "89118",
  timezone: "(GMT-08:00) Pacific Time",
  usr_number: "SB-2026-001",
  start_date: "2026-06-16",
  end_date: "2026-06-21",
  company_name: "Crimson Consulting",
  extra_locations: ["Top Golf, Las Vegas, NV"],
  staffing: { agents: 1, medics: 0, security: 0, total: 1 },
};

const assignments = [
  {
    role: "agent",
    work_date: "2026-06-16",
    end_date: "2026-06-18",
    start_time: "07:00",
    end_time: "17:00",
    position: null,
  },
];

describe("buildWorkPeriodLabelFromDates", () => {
  it("rebuilds activation range labels with MM/DD/YYYY and day count", () => {
    expect(
      buildWorkPeriodLabelFromDates("2026-06-12", "2026-06-30", "06/12 – 06/29 Activation Days (20)"),
    ).toBe("06/12/2026 – 06/30/2026 Activation Days (19)");
  });

  it("keeps travel day wording for single-day travel periods", () => {
    expect(
      buildWorkPeriodLabelFromDates("2026-07-01", "2026-07-01", "06/30/2026 Travel Day"),
    ).toBe("07/01/2026 Travel Day");
  });
});

describe("renderSowDocumentHtml Lynn reference layout", () => {
  it("matches the Lynn Nicely letter structure and scope bullets", () => {
    const form = mergeSowFormData(
      {
        vendor_company_name: "Crimson Consulting",
        vendor_email: "admin@ccsnorth.com",
        client_company_name: "On Location",
        event_name: "WrestleMania 2025",
        primary_venue: "Allegiant Stadium",
        city: "Las Vegas",
        state: "NV",
        additional_locations: ["Top Golf, Las Vegas, NV", "WWE World Las Vegas, NV"],
        work_periods: [
          {
            id: "1",
            label: "4/12/2025 Travel Day",
            start_date: "2025-04-12",
            end_date: "2025-04-12",
            daily_rate: "300",
            rate_type: "Half Day",
          },
          {
            id: "2",
            label: "4/13 – 4/20 Activation Days (8)",
            start_date: "2025-04-13",
            end_date: "2025-04-20",
            daily_rate: "600",
            rate_type: "per day",
          },
        ],
        compensation_summary: "9 total days @ $5400",
        signatory_name: "John Hindy",
        sign_by_date: "2025-03-10",
        payroll_notes: "Payroll is processed on a biweekly cadence via direct deposit, following the below schedule:",
        payroll_periods: [
          { id: "pp1", period_start: "2025-04-13", period_end: "2025-04-26", pay_date: "2025-05-09" },
        ],
      },
      buildDefaultSowFormData(projectMeta, { name: "Lynn Nicely", email: "lynn@example.com" }, assignments),
    );

    const html = renderSowDocumentHtml({
      employeeName: "Lynn Nicely",
      project: projectMeta,
      form,
      generatedDate: "03/07/2025",
    });

    expect(html).toContain("Dear Lynn Nicely");
    expect(html).toContain("In partnership with On Location, Crimson Consulting is excited");
    expect(html).toContain("WrestleMania 2025 in Las Vegas, NV");
    expect(html).toContain("Location: Allegiant Stadium Las Vegas, NV");
    expect(html).toContain("04/12/2025 Travel Day $300 Half Day");
    expect(html).toContain("04/13/2025 – 04/20/2025 Activation Days (8) $600 per day");
    expect(html).toContain("Rate: 9 total days @ $5400");
    expect(html).toContain("following the below schedule:");
    expect(html).toContain("04/13/2025");
    expect(html).toContain("04/26/2025");
    expect(html).toContain("05/09/2025");
    expect(html).toContain('class="payroll"');
    expect(html).toContain("background: #000");
    expect(html).toContain("John Hindy");
    expect(html).toContain('href="mailto:admin@ccsnorth.com"');
    expect(html).toContain("03/10/2025");
    expect(html).not.toContain("<strong>");
    expect(html).not.toContain("Generated by SECURX");
  });
});

describe("buildDefaultSowFormData", () => {
  it("prefills vendor, venue, and work periods from project + assignments", () => {
    const form = buildDefaultSowFormData(
      projectMeta,
      { name: "Lynn Nicely", email: "lynn@example.com" },
      assignments,
    );

    expect(form.vendor_company_name).toBe("Crimson Consulting");
    expect(form.client_contact_name).toBe("Lynn Nicely");
    expect(form.event_name).toBe("Super Bowl");
    expect(form.primary_venue).toBe("Allegiant Stadium");
    expect(form.city).toBe("Las Vegas");
    expect(form.work_periods.length).toBe(1);
    expect(form.work_periods[0]?.start_date).toBe("2026-06-16");
    expect(form.work_periods[0]?.label).toContain("Activation Days (3)");
    expect(form.per_diem).toContain("$85");
  });
});

describe("formDataToSowRecord", () => {
  it("builds locations and schedule text for PDF output", () => {
    const defaults = buildDefaultSowFormData(
      projectMeta,
      { name: "Lynn Nicely", email: "lynn@example.com" },
      assignments,
    );
    const form = mergeSowFormData(
      {
        client_company_name: "On Location",
        compensation_summary: "9 total days @ $5400",
        work_periods: [
          {
            id: "1",
            label: "4/13 – 4/20 Activation Days (8)",
            start_date: "2026-04-13",
            end_date: "2026-04-20",
            daily_rate: "600",
            rate_type: "per day",
          },
        ],
      },
      defaults,
    );

    const record = formDataToSowRecord(form);
    expect(record.partner_name).toBe("On Location");
    expect(record.locations).toContain("Allegiant Stadium");
    expect(record.schedule_details).toContain("Activation Days");
    expect(record.schedule_details).toContain("$600");
    expect(record.total_rate).toBe("9 total days @ $5400");
  });
});

describe("mergeSowWithDefaults", () => {
  it("keeps stored values over defaults", () => {
    const defaults = buildDefaultSowContent(projectMeta, "Lynn Nicely", assignments);
    const merged = mergeSowWithDefaults(
      { total_rate: "Custom rate", partner_name: "On Location" },
      defaults,
    );
    expect(merged.total_rate).toBe("Custom rate");
    expect(merged.partner_name).toBe("On Location");
    expect(merged.per_diem).toBe(defaults.per_diem);
  });
});

describe("mergeSowFormData", () => {
  it("fills empty stored location fields from project defaults", () => {
    const defaults = buildDefaultSowFormData(
      { ...projectMeta, address: "100 Wall Street", address_2: "Suite 2800" },
      { name: "Lynn Nicely", email: "lynn@example.com" },
      assignments,
    );
    const merged = mergeSowFormData(
      {
        primary_venue: "",
        venue_address: "",
        city: "",
        state: "",
        zip_code: "",
        timezone: "",
      },
      defaults,
    );

    expect(merged.primary_venue).toBe("Allegiant Stadium");
    expect(merged.venue_address).toBe("100 Wall Street, Suite 2800");
    expect(merged.city).toBe("Las Vegas");
    expect(merged.state).toBe("NV");
    expect(merged.zip_code).toBe("89118");
    expect(merged.timezone).toBe("(GMT-08:00) Pacific Time");
  });

  it("fills empty stored per diem and dress code from project defaults", () => {
    const defaults = buildDefaultSowFormData(
      {
        ...projectMeta,
        sow_per_diem: "On Location will provide meals where applicable.",
        sow_dress_code: "Dark suit and dress shoes.",
      },
      { name: "Lynn Nicely", email: "lynn@example.com" },
      assignments,
    );
    const merged = mergeSowFormData({ per_diem: "", dress_code: "" }, defaults);
    expect(merged.per_diem).toContain("On Location will provide meals");
    expect(merged.dress_code).toBe("Dark suit and dress shoes.");
  });
});

describe("formatGanttLocationLine", () => {
  it("formats city and state for additional locations", () => {
    expect(
      formatGanttLocationLine({
        name: "Top Golf",
        city: "Las Vegas",
        state: "NV",
      }),
    ).toBe("Top Golf, Las Vegas, NV");
  });
});

describe("parseFormDataJson", () => {
  it("returns null for invalid input", () => {
    expect(parseFormDataJson(null)).toBeNull();
    expect(parseFormDataJson("bad")).toBeNull();
  });

  it("returns object for valid JSON shape", () => {
    const form = buildDefaultSowFormData(projectMeta, { name: "A", email: "a@b.com" }, []);
    expect(parseFormDataJson(form)?.event_name).toBe("Super Bowl");
  });
});

describe("sowRecordToFormHints", () => {
  it("ignores legacy auto-generated rate and per diem text", () => {
    const defaults = buildDefaultSowFormData(projectMeta, { name: "Aisha Johnson", email: "a@b.com" }, assignments);
    const hints = sowRecordToFormHints(
      {
        partner_name: null,
        locations: null,
        schedule_details: null,
        total_rate: "26 total days assigned",
        per_diem: "Meals will be provided where applicable.",
        dress_code: null,
        policies: null,
        travel_notes: null,
        payroll_notes: null,
        sign_by_date: null,
        status: "draft",
        signed_at: null,
        signed_file_path: null,
      },
      defaults,
    );
    expect(hints.compensation_summary).not.toContain("assigned");
    expect(hints.per_diem).toContain("On Location will provide meals");
  });
});

describe("renderSowHtml", () => {
  it("includes employee name, company, and compensation in HTML", () => {
    const form = buildDefaultSowFormData(projectMeta, { name: "Lynn Nicely", email: "lynn@example.com" }, assignments);
    const mergedForm = mergeSowFormData(
      {
        compensation_summary: "9 total days @ $5400",
        client_company_name: "On Location",
        vendor_email: "admin@ccsnorth.com",
        signatory_name: "John Hindy",
        payroll_periods: [
          { id: "1", period_start: "2026-04-13", period_end: "2026-04-20", pay_date: "2026-04-25" },
        ],
      },
      form,
    );
    const record = formDataToSowRecord(mergedForm);
    const html = renderSowHtml({
      employeeName: "Lynn Nicely",
      project: projectMeta,
      sow: { ...record, status: "draft", signed_at: null, signed_file_path: null },
      form: mergedForm,
      vendorCompany: "Crimson Consulting",
      signatoryName: "John Hindy",
    });

    expect(html).toContain("Dear Lynn Nicely");
    expect(html).toContain("Crimson Consulting");
    expect(html).toContain("On Location");
    expect(html).toContain("Super Bowl");
    expect(html).toContain("9 total days @ $5400");
    expect(html).toContain("John Hindy");
    expect(html).toContain("PAY PERIOD START");
    expect(html).toContain("admin@ccsnorth.com");
    expect(html).toContain("The scope of work is as follows:");
    expect(html).not.toContain("Generated by SECURX");
    expect(html).toContain("<!DOCTYPE html>");
  });
});
