import type { SeatmapOverviewPayload, SeatmapTemplateRow } from "@/lib/event-platform/seatmaps/seatmap-overview-types";

const ACTIVE_MAPS: SeatmapTemplateRow[] = [
  {
    id: "demo-1",
    name: "Main Arena",
    updatedAt: "2026-05-10",
    createdAt: "2026-01-15",
    category: "Concert",
    mapType: "Arena",
    seatCount: 2450,
    usedInEvents: 8,
    status: "active",
    sectionCount: 18,
    rowCount: 34,
    previewVariant: "arena",
  },
  {
    id: "demo-2",
    name: "Conference Hall A",
    updatedAt: "2026-04-28",
    createdAt: "2026-02-01",
    category: "Conference",
    mapType: "Theater",
    seatCount: 320,
    usedInEvents: 5,
    status: "active",
    sectionCount: 6,
    rowCount: 12,
    previewVariant: "theater",
  },
  {
    id: "demo-3",
    name: "Outdoor Amphitheater",
    updatedAt: "2026-04-15",
    createdAt: "2026-01-20",
    category: "Concert",
    mapType: "Amphitheater",
    seatCount: 1800,
    usedInEvents: 6,
    status: "active",
    sectionCount: 12,
    rowCount: 28,
    previewVariant: "arena",
  },
  {
    id: "demo-4",
    name: "Banquet Hall",
    updatedAt: "2026-04-05",
    createdAt: "2026-03-01",
    category: "Banquet",
    mapType: "Banquet",
    seatCount: 400,
    usedInEvents: 3,
    status: "active",
    sectionCount: 4,
    rowCount: 10,
    previewVariant: "general",
  },
  {
    id: "demo-5",
    name: "VIP Lounge",
    updatedAt: "2026-03-22",
    createdAt: "2026-02-10",
    category: "Special",
    mapType: "Lounge",
    seatCount: 120,
    usedInEvents: 2,
    status: "draft",
    sectionCount: 2,
    rowCount: 6,
    previewVariant: "general",
  },
  {
    id: "demo-6",
    name: "Exhibition Floor",
    updatedAt: "2026-03-10",
    createdAt: "2026-01-05",
    category: "Exhibition",
    mapType: "General",
    seatCount: 3000,
    usedInEvents: 7,
    status: "active",
    sectionCount: 8,
    rowCount: 20,
    previewVariant: "general",
  },
  {
    id: "demo-7",
    name: "Stadium West Wing",
    updatedAt: "2026-02-28",
    createdAt: "2025-11-12",
    category: "Concert",
    mapType: "Arena",
    seatCount: 1200,
    usedInEvents: 4,
    status: "active",
    sectionCount: 10,
    rowCount: 22,
    previewVariant: "arena",
  },
  {
    id: "demo-8",
    name: "Training Room B",
    updatedAt: "2026-02-14",
    createdAt: "2026-01-08",
    category: "Conference",
    mapType: "Theater",
    seatCount: 180,
    usedInEvents: 1,
    status: "active",
    sectionCount: 3,
    rowCount: 8,
    previewVariant: "theater",
  },
  {
    id: "demo-9",
    name: "Rooftop Terrace",
    updatedAt: "2026-02-01",
    createdAt: "2025-12-20",
    category: "Special",
    mapType: "General",
    seatCount: 96,
    usedInEvents: 2,
    status: "draft",
    sectionCount: 2,
    rowCount: 4,
    previewVariant: "general",
  },
  {
    id: "demo-10",
    name: "Community Center",
    updatedAt: "2026-01-18",
    createdAt: "2025-10-01",
    category: "Conference",
    mapType: "Theater",
    seatCount: 512,
    usedInEvents: 3,
    status: "active",
    sectionCount: 5,
    rowCount: 14,
    previewVariant: "theater",
  },
  {
    id: "demo-11",
    name: "Festival Grounds",
    updatedAt: "2026-01-05",
    createdAt: "2025-09-15",
    category: "Concert",
    mapType: "Amphitheater",
    seatCount: 2200,
    usedInEvents: 5,
    status: "active",
    sectionCount: 14,
    rowCount: 30,
    previewVariant: "arena",
  },
  {
    id: "demo-12",
    name: "Workshop Studio",
    updatedAt: "2025-12-20",
    createdAt: "2025-08-22",
    category: "Conference",
    mapType: "General",
    seatCount: 64,
    usedInEvents: 1,
    status: "active",
    sectionCount: 1,
    rowCount: 4,
    previewVariant: "general",
  },
];

const ARCHIVED_MAPS: SeatmapTemplateRow[] = [
  {
    id: "demo-arch-1",
    name: "Legacy Ballroom",
    updatedAt: "2025-11-01",
    createdAt: "2025-03-01",
    category: "Banquet",
    mapType: "Banquet",
    seatCount: 250,
    usedInEvents: 0,
    status: "archived",
    sectionCount: 3,
    rowCount: 8,
    previewVariant: "general",
  },
];

export function seatmapOverviewDemo(): SeatmapOverviewPayload {
  return {
    ok: true,
    isDemo: true,
    kpis: {
      totalMaps: 12,
      totalMapsSub: "Active templates",
      totalSeats: 8452,
      totalSeatsSub: "Across all maps",
      usageCount: 34,
      usageSub: "Used in events",
      avgOccupancy: 67,
      avgOccupancySub: "Across events",
      sectionCount: 56,
      sectionSub: "Across all maps",
    },
    activeMaps: ACTIVE_MAPS,
    archivedMaps: ARCHIVED_MAPS,
    activeTotal: ACTIVE_MAPS.length,
  };
}
