import { NextResponse, type NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { getProjectOpsContext } from "@/lib/project-operations-api";
import { calcHoursFromTimes, eachDateInRange } from "@/lib/project-staff-hours";

export const dynamic = "force-dynamic";

export async function GET(req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const { id } = await ctx.params;
  const projectId = BigInt(id);
  const auth = await getProjectOpsContext(req, projectId);
  if ("error" in auth) return NextResponse.json({ error: auth.error }, { status: auth.status });

  const date = req.nextUrl.searchParams.get("date");
  if (!date || !/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    return NextResponse.json({ error: "date required (YYYY-MM-DD)" }, { status: 400 });
  }

  const project = await prisma.project.findFirst({
    where: { id: projectId },
    select: { name: true },
  });
  if (!project) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const rows = await prisma.projectStaffAssignment.findMany({ where: { projectId } });
  const userIds = rows.map((r) => r.userId);
  const users = userIds.length
    ? await prisma.user.findMany({
        where: { id: { in: userIds } },
        select: { id: true, name: true, email: true },
      })
    : [];
  const userMap = new Map(users.map((u) => [u.id, u]));

  const entries: Array<{ name: string; role: string; hours: number; position: string }> = [];
  for (const r of rows) {
    if (!r.workDate) continue;
    const start = r.workDate.toISOString().slice(0, 10);
    const end = r.endDate?.toISOString().slice(0, 10) ?? start;
    const dates = eachDateInRange(start, end);
    if (!dates.includes(date)) continue;
    const u = userMap.get(r.userId);
    entries.push({
      name: u?.name ?? u?.email ?? "Unknown",
      role: r.role,
      hours: calcHoursFromTimes(r.startTime, r.endTime),
      position: r.position ?? "—",
    });
  }

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Timesheet ${date}</title>
<style>
  body { font-family: Arial, sans-serif; padding: 24px; color: #111; }
  h1 { font-size: 18px; margin-bottom: 4px; }
  .sub { color: #555; font-size: 13px; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; }
  th, td { border: 1px solid #ccc; padding: 8px; text-align: left; font-size: 13px; }
  th { background: #f3f4f6; }
</style></head><body>
<h1>Conference Timesheet</h1>
<div class="sub">${project.name} — ${date}</div>
<table>
<thead><tr><th>Name</th><th>Type</th><th>Position</th><th>Hours</th></tr></thead>
<tbody>
${entries.map((e) => `<tr><td>${e.name}</td><td>${e.role}</td><td>${e.position}</td><td>${e.hours}</td></tr>`).join("")}
</tbody>
</table>
<p style="margin-top:16px;font-size:12px;color:#666;">Generated by SECURX Projects</p>
</body></html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `inline; filename="timesheet-${date}.html"`,
    },
  });
}
