-- Event plant inventory, requests, and game assignments

CREATE TABLE IF NOT EXISTS `event_plants` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT NOT NULL,
  `event_id` BIGINT NOT NULL,
  `pos_product_id` BIGINT NULL,
  `event_vendor_id` BIGINT NULL,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(128) NULL,
  `variety` VARCHAR(128) NULL,
  `description` TEXT NULL,
  `image_url` VARCHAR(2048) NULL,
  `quantity_purchased` INT NOT NULL DEFAULT 0,
  `quantity_assigned` INT NOT NULL DEFAULT 0,
  `quantity_awarded` INT NOT NULL DEFAULT 0,
  `quantity_removed` INT NOT NULL DEFAULT 0,
  `unit_cost` DECIMAL(12, 2) NOT NULL DEFAULT 0,
  `retail_value` DECIMAL(12, 2) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'available',
  `notes` TEXT NULL,
  `created_by_id` BIGINT NULL,
  `updated_by_id` BIGINT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `event_plants_organization_id_event_id_status_idx` (`organization_id`, `event_id`, `status`),
  CONSTRAINT `event_plants_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_plants_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `lms_events`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_plants_event_vendor_id_fkey` FOREIGN KEY (`event_vendor_id`) REFERENCES `event_vendors`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `event_plants_created_by_id_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_plant_requests` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT NOT NULL,
  `event_id` BIGINT NOT NULL,
  `registration_id` BIGINT NOT NULL,
  `event_plant_id` BIGINT NULL,
  `requested_plant_name` VARCHAR(255) NULL,
  `priority` INT NULL DEFAULT 1,
  `notes` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `event_plant_requests_organization_id_event_id_idx` (`organization_id`, `event_id`),
  INDEX `event_plant_requests_registration_id_idx` (`registration_id`),
  INDEX `event_plant_requests_event_plant_id_idx` (`event_plant_id`),
  CONSTRAINT `event_plant_requests_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_plant_requests_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `lms_events`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_plant_requests_registration_id_fkey` FOREIGN KEY (`registration_id`) REFERENCES `lms_event_registrations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_plant_requests_event_plant_id_fkey` FOREIGN KEY (`event_plant_id`) REFERENCES `event_plants`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_plant_assignments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT NOT NULL,
  `event_id` BIGINT NOT NULL,
  `event_plant_id` BIGINT NOT NULL,
  `round_instance_id` BIGINT NULL,
  `bingo_game_id` BIGINT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `status` VARCHAR(32) NOT NULL DEFAULT 'assigned',
  `assigned_by_id` BIGINT NULL,
  `assigned_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `event_plant_assignments_organization_id_event_id_idx` (`organization_id`, `event_id`),
  INDEX `event_plant_assignments_event_plant_id_idx` (`event_plant_id`),
  INDEX `event_plant_assignments_round_instance_id_idx` (`round_instance_id`),
  CONSTRAINT `event_plant_assignments_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_plant_assignments_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `lms_events`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_plant_assignments_event_plant_id_fkey` FOREIGN KEY (`event_plant_id`) REFERENCES `event_plants`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_plant_assignments_round_instance_id_fkey` FOREIGN KEY (`round_instance_id`) REFERENCES `event_bingo_round_instances`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `event_plant_assignments_bingo_game_id_fkey` FOREIGN KEY (`bingo_game_id`) REFERENCES `event_bingo_games`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `event_plant_assignments_assigned_by_id_fkey` FOREIGN KEY (`assigned_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
